import { THREE, createGame, box, sphere, cylinder, label, clearGroup } from '../arcade-runtime/runtime.mjs';
import { BIOMES, TOWERS, ENEMIES, levelConfig, createBattle, stepBattle, buildTower, upgradeTower, upgradeCost, towerStats, sellTower, startWave, castSkill, sanitizeSave, settleBattle, buyResearch } from './core.mjs';
const game = createGame({ id: 'pocket-bastion', title: '口袋防线', subtitle: 'POCKET BASTION / HOLD THE GATE', accent: '#e0c998', background: 0x303b44, help: '点击编号基座建塔或升级。方向键切换基座，Space 建造。N 下一波；E 准备流星，再点击战场释放，或 Space 自动瞄准敌群。塔会自动攻击。火克木、水克火、雷克水、光克暗；潮湿配合冰冻与雷电。分支在二级之后选择。P / Esc 暂停，手机可使用编号菜单精确选择基座。' });
game.controls([{ code: 'Space', label: '建造' }, { code: 'KeyN', label: '号角' }, { code: 'KeyE', label: '流星' }]);
let save = sanitizeSave(game.load(null)), state, selectedLevel = 0, challenge = 'standard', selectedSlot = 0, skillArmed = false, lastPhase = '', world, units, selection, skillCircle, lastSound = 0, pointerWorld = { x: 0, z: 0 };
const cache = new Map(), padMeshes = [], ray = new THREE.Raycaster(), ground = new THREE.Plane(new THREE.Vector3(0, 1, 0), -.15), hitPoint = new THREE.Vector3();
const dock = document.createElement('div'); dock.className = 'bastion-dock'; dock.innerHTML = '<select aria-label="选择建造位" id="pad-select"></select><button class="build-button">建造 / 升级</button><button class="wave-button">吹响号角</button><button class="meteor-button">流星</button>'; document.body.append(dock);
const mat = (color, opts = {}) => new THREE.MeshStandardMaterial({ color, roughness: .72, metalness: .15, ...opts });
function mesh(parent, geo, color, x = 0, y = 0, z = 0, opts = {}) { const m = new THREE.Mesh(geo, mat(color, opts)); m.position.set(x, y, z); m.castShadow = true; m.receiveShadow = true; parent.add(m); return m; }
function ring(parent, r, tube, color, y) { const m = mesh(parent, new THREE.TorusGeometry(r, tube, 6, 40), color, 0, y, 0, { emissive: color, emissiveIntensity: .15 }); m.rotation.x = Math.PI / 2; return m; }
function rod(parent, a, b, width, color) { const d = new THREE.Vector3().subVectors(b, a); const obj = cylinder(parent, 0, 0, 0, width, width, d.length(), color, { segments: 7 }); obj.position.copy(a).add(b).multiplyScalar(.5); obj.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), d.normalize()); return obj; }
function rock(parent, x, y, z, size, color, seed) { const r = mesh(parent, new THREE.DodecahedronGeometry(size), color, x, y, z); r.scale.set(1.1, .72, .85); r.rotation.set(seed * .21, seed * .61, seed * .11); return r; }
function gem(parent, x, y, z, size, color) { const m = mesh(parent, new THREE.OctahedronGeometry(size), color, x, y, z, { roughness: .2, metalness: .4, emissive: color, emissiveIntensity: .3 }); m.scale.y = 1.6; return m; }
function wallTower(parent, x, z, height) { cylinder(parent, x, height / 2, z, .65, .85, height, 0xb5ac95, { segments: 10 }); cylinder(parent, x, height + .04, z, .85, .75, .25, 0xc8c0a7, { segments: 10 }); for (let i = 0; i < 6; i++) { const a = i / 6 * Math.PI * 2; box(parent, x + Math.cos(a) * .61, height + .35, z + Math.sin(a) * .61, .25, .5, .3, 0xc8c0a7); } }
function scenery() {
  clearGroup(game.world); cache.clear(); padMeshes.length = 0; world = new THREE.Group(); units = new THREE.Group(); game.world.add(world, units); const cfg = state.config, bio = BIOMES[cfg.biome];
  game.scene.background.setHex([0x344b49, 0x514035, 0x2c4d5b, 0x465369, 0x383647][cfg.biome]); game.scene.fog.color.copy(game.scene.background); game.scene.fog.near = 95; game.scene.fog.far = 240;
  box(world, 0, -1, 0, 31, 1.8, 21.5, 0x3e4845); box(world, 0, -.12, 0, 30.6, .45, 21, bio.color, { roughness: .94 });
  for (let i = 0; i < 48; i++) { const x = (i % 12 - 5.5) * 2.7, z = i < 24 ? -10.4 : 10.4; rock(world, x, -.5, z, .9, 0x414b47, i); }
  const pathColor = [0xb0a588, 0xc79868, 0x8ea5a7, 0xb6bdc4, 0xa292b3][cfg.biome];
  for (const [routeIndex, path] of cfg.paths.entries()) for (let i = 1; i < path.length; i++) {
    const a = path[i - 1], b = path[i], len = Math.hypot(b[0] - a[0], b[1] - a[1]), angle = Math.atan2(b[0] - a[0], b[1] - a[1]);
    const road = box(world, (a[0] + b[0]) / 2, .15 + routeIndex * .025, (a[1] + b[1]) / 2, 1.8, .15, len + .6, pathColor, { roughness: .96 }); road.rotation.y = angle;
    for (let k = 0; k < len; k += 1.5) { const x = a[0] + (b[0] - a[0]) * k / len, z = a[1] + (b[1] - a[1]) * k / len; const slab = box(world, x, .24 + routeIndex * .025, z, 1.55, .045, .5, routeIndex ? 0xb4b4a4 : 0xd0c3a3); slab.rotation.y = angle + Math.sin(k) * .06; }
  }
  for (const [i, path] of cfg.paths.entries()) { const [x, z] = path[0]; const g = new THREE.Group(); g.position.set(x + 1.1, .1, z); world.add(g); const r = mesh(g, new THREE.TorusGeometry(1.08, .15, 8, 32), 0xb5b3c1, 0, 1.1, 0, { emissive: 0x856378, emissiveIntensity: .5 }); r.rotation.y = Math.PI / 2; label(world, `入口 ${i + 1}`, x + .9, 3, z, { color: '#f6bea1', size: .45 }); }
  const gate = new THREE.Group(); gate.position.set(12.2, .15, 0); world.add(gate); wallTower(gate, 0, -1.65, 3.2); wallTower(gate, 0, 1.65, 3.2); box(gate, .4, 2.8, 0, .9, .6, 3.3, 0xc6bca4); for (let i = 0; i < 4; i++) cylinder(gate, 0, 1.15, -.75 + i * .5, .06, .06, 2.1, 0x6d7874); const banner = box(gate, -.4, 3.1, 0, .12, 1.5, 1.1, 0x778d93); banner.rotation.z = -.12; gem(gate, -.5, 3.15, 0, .27, 0xf2d69c); label(world, '守望城门', 12.3, 4.8, 0, { size: .52, color: '#fff0c4' });
  for (const [i, pad] of cfg.pads.entries()) { const g = new THREE.Group(); g.position.set(pad.x, .16, pad.z); world.add(g); cylinder(g, 0, .14, 0, .9, 1, .28, 0x687774, { segments: 8 }); const top = cylinder(g, 0, .31, 0, .79, .84, .12, 0xc0bba4, { segments: 8 }); ring(g, .68, .035, 0xe0d4a5, .4); label(g, String(i + 1).padStart(2, '0'), 0, .82, 0, { size: .42, color: '#fff8d4' }); padMeshes.push(top); }
  for (let i = 0; i < 36; i++) { const x = Math.sin(i * 9.2) * 13, z = Math.cos(i * 5.9) * 9; if (cfg.pads.some(p => Math.hypot(x - p.x, z - p.z) < 1.5)) continue; if (cfg.paths.some(path => path.some(p => Math.hypot(x - p[0], z - p[1]) < 2.2))) continue;
    if (cfg.biome === 0) { cylinder(world, x, .5, z, .07, .15, 1, 0x776852, { segments: 5 }); for (let j = 0; j < 2; j++) mesh(world, new THREE.ConeGeometry(.55 - j * .1, 1.15, 6), j ? 0x779487 : 0x4a7060, x, 1.1 + j * .6, z); }
    else if (cfg.biome === 1) { const r = rock(world, x, .4, z, .6, 0x9b7a5e, i); r.scale.y = 1.6; }
    else if (cfg.biome === 2) { cylinder(world, x, .13, z, .8, .8, .03, 0x608f9c, { opacity: .6 }); for (let j = 0; j < 3; j++) cylinder(world, x + j * .15, .5, z, .025, .04, .8, 0xb7b698, { segments: 4 }); }
    else if (cfg.biome === 3) { rock(world, x, .2, z, .7, 0xe0e1d5, i); if (i % 2 === 0) gem(world, x, .8, z, .4, 0xb0d9e7); }
    else { const c = gem(world, x, .7, z, .5, 0x9786b0); c.rotation.z = .4; }
  }
  selection = new THREE.Group(); ring(selection, 1.05, .075, 0xf5d994, .55); world.add(selection); skillCircle = new THREE.Group(); ring(skillCircle, 3.8, .1, 0xffb57e, .5); skillCircle.visible = false; world.add(skillCircle);
  document.querySelector('#pad-select').innerHTML = cfg.pads.map((_, i) => `<option value="${i}">基座 ${String(i + 1).padStart(2, '0')}</option>`).join(''); selectedSlot = Math.min(selectedSlot, cfg.pads.length - 1); document.querySelector('#pad-select').value = String(selectedSlot);
}
function makeTower(t) {
  const def = TOWERS.find(x => x.id === t.type), g = new THREE.Group(), head = new THREE.Group(); g.add(head); head.position.y = .55;
  cylinder(g, 0, .28, 0, .65, .78, .55, 0x7f8780, { segments: 8 }); ring(g, .68, .04, def.color, .46);
  if (t.type === 'arrow') { for (const side of [-1, 1]) cylinder(head, side * .35, .6, 0, .08, .11, 1.2, 0x86755a, { segments: 6 }); box(head, 0, 1.1, 0, 1, .17, .72, 0xb5a07a); const bow = mesh(head, new THREE.TorusGeometry(.63, .065, 6, 20, Math.PI), 0xe0cfaa, 0, 1.3, .25); bow.rotation.z = Math.PI; rod(head, new THREE.Vector3(-.63, 1.3, .25), new THREE.Vector3(.63, 1.3, .25), .017, 0xe8d9b7); const barrel = cylinder(head, 0, 1.35, .1, .09, .11, 1.35, 0x596a69); barrel.rotation.x = Math.PI / 2; }
  if (t.type === 'fire') { cylinder(head, 0, .55, 0, .55, .6, 1.1, 0x75635a, { segments: 10 }); cylinder(head, 0, 1.15, 0, .65, .5, .3, 0xbbb2a0, { segments: 10 }); sphere(head, 0, 1.42, 0, .37, 0xf6bd70, { emissive: 0xff903b, emissiveIntensity: 1 }); for (let i = 0; i < 4; i++) { const a = i / 4 * Math.PI * 2; cylinder(head, Math.cos(a) * .44, 1.55, Math.sin(a) * .44, .07, .1, 1, 0x6f655c); } }
  if (t.type === 'frost') { cylinder(head, 0, .38, 0, .6, .48, .75, 0xa6bdc1, { segments: 6 }); for (let i = 0; i < 5; i++) gem(head, Math.cos(i * 1.256) * .38, .95, Math.sin(i * 1.256) * .38, .27, def.color); gem(head, 0, 1.42, 0, .53, 0xd3eff9); }
  if (t.type === 'storm') { cylinder(head, 0, .8, 0, .2, .4, 1.6, 0x818b88); for (let i = 0; i < 4; i++) ring(head, .43 - i * .045, .075, 0xc4bba0, .45 + i * .3); sphere(head, 0, 1.75, 0, .36, def.color, { metalness: .6, emissive: 0x9e7ac2, emissiveIntensity: .5 }); }
  if (t.type === 'thorn') { cylinder(head, 0, .38, 0, .62, .47, .75, 0x9b8567, { segments: 9 }); for (let i = 0; i < 6; i++) { const leaf = sphere(head, Math.cos(i) * .3, .85, Math.sin(i) * .3, .4, def.color); leaf.scale.set(.4, .8, .7); leaf.rotation.z = Math.cos(i) * .6; } cylinder(head, 0, 1.22, 0, .07, .14, 1, 0x6c8d58); sphere(head, 0, 1.6, 0, .32, 0xc4d892); }
  if (t.type === 'light') { cylinder(head, 0, .65, 0, .28, .6, 1.3, 0xb8b8a5, { segments: 6 }); const halo = mesh(head, new THREE.TorusGeometry(.65, .06, 6, 30), 0xead6a2, 0, 1.55, 0); halo.rotation.y = .2; gem(head, 0, 1.55, 0, .38, 0xfff1b9); }
  if (t.type === 'mortar') { for (const side of [-1, 1]) { const wheel = cylinder(head, side * .48, .4, 0, .35, .35, .17, 0x65685f, { segments: 10 }); wheel.rotation.z = Math.PI / 2; } const barrel = cylinder(head, 0, .8, .15, .38, .3, 1.25, 0x919c96, { metalness: .5, roughness: .35 }); barrel.rotation.x = Math.PI / 4; const mouth = cylinder(head, 0, 1.25, .59, .25, .25, .035, 0x26363a); mouth.rotation.x = Math.PI / 4; }
  if (t.type === 'water') { cylinder(head, 0, .5, 0, .28, .6, 1, 0x91a9a1, { segments: 8 }); for (let i = 0; i < 6; i++) { const petal = sphere(head, Math.cos(i) * .38, 1.1, Math.sin(i) * .38, .4, i % 2 ? 0xc0dfc6 : 0x8dc5bd); petal.scale.set(.6, .22, 1); petal.rotation.y = -i; } sphere(head, 0, 1.45, 0, .28, 0x94e2df, { transparent: true, opacity: .8, emissive: 0x57a5aa }); }
  if (t.level >= 2) { ring(g, .73, .04, 0xf3dca7, .62); for (let i = 0; i < (t.level === 3 ? 4 : 2); i++) gem(g, Math.cos(i * Math.PI / 2) * .63, .68, Math.sin(i * Math.PI / 2) * .63, .12, def.color); }
  g.userData.head = head; g.userData.signature = `${t.type}:${t.level}:${t.branch}`; return g;
}
function makeEnemy(e) {
  const g = new THREE.Group(), color = { scout: 0xbcae8b, runner: 0x9eb880, plated: 0x8e9a99, ember: 0xc58162, tide: 0x83b8c4, healer: 0xbdc69a, shade: 0xa091b1, boss: 0x8a8593 }[e.kind];
  if (e.kind === 'runner' || e.kind === 'shade') { const body = sphere(g, 0, .7, 0, .38, color); body.scale.set(.72, .72, 1.2); for (const side of [-1, 1]) { const wing = sphere(g, side * .42, .85, -.05, .48, e.kind === 'shade' ? 0xc4b1d3 : 0xd7ddba); wing.scale.set(1, .1, .55); wing.rotation.z = side * .25; } }
  else if (e.kind === 'plated' || e.kind === 'boss') { const shell = mesh(g, new THREE.DodecahedronGeometry(e.kind === 'boss' ? .95 : .65), color, 0, .7, 0, { metalness: .3 }); shell.scale.set(1, .8, 1.25); for (const side of [-1, 1]) for (const z of [-.45, .45]) { const wheel = cylinder(g, side * .52, .28, z, .25, .25, .16, 0x44575a); wheel.rotation.z = Math.PI / 2; } for (const side of [-1, 1]) { const horn = mesh(g, new THREE.ConeGeometry(.12, .5, 5), 0xede0c4, side * .4, .9, .7); horn.rotation.x = Math.PI / 3; } if (e.kind === 'boss') { for (let i = 0; i < 4; i++) gem(g, (i - 1.5) * .35, 1.6, -.2, .22, 0xcab3d0); ring(g, 1, .04, 0xe6b1a0, .15); } }
  else { cylinder(g, 0, .58, 0, .25, .37, .85, color, { segments: 7 }); sphere(g, 0, 1.12, 0, .28, 0xd6cbb0); for (const side of [-1, 1]) { const leg = sphere(g, side * .18, .18, 0, .16, 0x536365); leg.scale.z = 1.35; } if (e.kind === 'healer') { cylinder(g, .4, .9, 0, .035, .05, 1.6, 0x8b8f71); gem(g, .4, 1.76, 0, .19, 0xd5e4ac); } if (e.kind === 'ember') sphere(g, 0, 1.4, 0, .17, 0xffc78d, { emissive: 0xf19549 }); if (e.kind === 'tide') { const hood = sphere(g, 0, 1.15, -.05, .34, 0x98c8d2, { opacity: .7 }); hood.scale.y = 1.2; } }
  for (const side of [-1, 1]) sphere(g, side * .1, e.kind === 'plated' || e.kind === 'boss' ? .7 : 1.14, e.kind === 'runner' || e.kind === 'shade' ? .31 : .24, .038, 0xffd69a, { emissive: 0xd9a577 });
  const health = box(g, 0, e.kind === 'boss' ? 2.1 : 1.65, 0, e.kind === 'boss' ? 1.9 : .8, .055, .065, 0xf3b49b); g.userData.health = health; return g;
}
function remove(obj) { obj.parent?.remove(obj); clearGroup(obj); }
function sync(prefix, items, create, update, signature = null) {
  const alive = new Set(); for (const e of items) { const key = prefix + ':' + e.id; alive.add(key); let obj = cache.get(key); if (obj && signature && obj.userData.signature !== signature(e)) { remove(obj); cache.delete(key); obj = null; } if (!obj) { obj = create(e); units.add(obj); cache.set(key, obj); } update(obj, e); }
  for (const [key, obj] of cache) if (key.startsWith(prefix + ':') && !alive.has(key)) { remove(obj); cache.delete(key); }
}
function effectMesh(e) { const g = new THREE.Group(); if (['shot', 'beam'].includes(e.kind)) { rod(g, new THREE.Vector3(e.x, 1.6, e.z), new THREE.Vector3(e.toX, .9, e.toZ), e.kind === 'beam' ? .045 : .027, e.color); } else if (e.kind === 'arc') { sphere(g, 0, 0, 0, .17, 0xf2d39d, { emissive: 0xc3a069 }); } else { g.position.set(e.x, .3, e.z); ring(g, 1, .06, e.color, .1); if (e.kind === 'meteor' || e.kind === 'explosion') { const flame = sphere(g, 0, .3, 0, .5, e.color, { emissive: e.color, emissiveIntensity: .8 }); flame.scale.y = 1.7; } } return g; }
function render(dt) {
  const pad = state.config.pads[selectedSlot]; if (pad) selection.position.set(pad.x, .15, pad.z); selection.rotation.y = state.time * .25;
  skillCircle.visible = skillArmed; skillCircle.position.set(pointerWorld.x, .1, pointerWorld.z);
  sync('tower', state.towers, makeTower, (obj, t) => { obj.position.set(t.x, .43, t.z); obj.userData.head.rotation.y = t.angle || 0; obj.userData.head.position.y = .55 - (t.fired || 0) * .35; }, t => `${t.type}:${t.level}:${t.branch}`);
  sync('enemy', state.enemies, makeEnemy, (obj, e) => { const previous = obj.position.clone(); obj.position.set(e.x, .23 + (e.kind === 'runner' || e.kind === 'shade' ? Math.sin(state.time * 8 + e.id) * .09 : 0), e.z); if (previous.distanceTo(obj.position) > .001) obj.rotation.y = Math.atan2(e.x - previous.x, e.z - previous.z); obj.userData.health.scale.x = Math.max(.01, e.hp / e.maxHp); obj.userData.health.visible = e.hp < e.maxHp; });
  sync('effect', state.effects, effectMesh, (obj, e) => { const f = 1 - e.ttl / e.life; if (e.kind === 'arc') obj.position.set(e.x + (e.toX - e.x) * f, 1.4 + Math.sin(f * Math.PI) * 3, e.z + (e.toZ - e.z) * f); else if (!['shot', 'beam'].includes(e.kind)) obj.scale.setScalar(e.radius * (.5 + f * .5)); obj.traverse(m => { if (m.material) { m.material.transparent = true; m.material.opacity = (1 - f) * .8; m.material.depthWrite = false; } }); });
  const aspect = game.camera.aspect, distance = Math.max(34, 18.2 / (Math.tan(game.camera.fov * Math.PI / 360) * aspect)); const target = new THREE.Vector3(0, distance * .81, distance * .61); game.camera.position.lerp(target, Math.min(1, dt * 8)); game.camera.lookAt(0, .1, 0);
  game.ui.stats([{ label: '城门', value: state.lives }, { label: '金币', value: state.gold }, { label: '波次', value: `${state.wave} / ${state.config.waves.length}` }, { label: '击退', value: state.kills }, { label: '关卡', value: String(state.config.index + 1).padStart(2, '0') }]);
  dock.querySelector('.wave-button').textContent = state.phase === 'build' ? state.wave ? '下一波 · N' : '吹响号角 · N' : `战斗中 · ${state.enemies.length + state.queue.length}`; dock.querySelector('.wave-button').disabled = state.phase !== 'build'; dock.querySelector('.meteor-button').textContent = skillArmed ? '取消流星' : state.skillCooldown > 0 ? `流星 ${Math.ceil(state.skillCooldown)}s` : '流星就绪 · E'; dock.querySelector('.meteor-button').classList.toggle('armed', skillArmed);
  game.ui.hint(skillArmed ? '点击战场释放流星 · Space 自动瞄准敌群 · E 取消' : `点击编号基座建塔 · 方向键选择 · Space 建造 · ${state.config.rule}`);
}
function setSlot(value) { selectedSlot = (value + state.config.pads.length) % state.config.pads.length; document.querySelector('#pad-select').value = String(selectedSlot); }
function start() { state = createBattle({ level: selectedLevel, challenge, save }); selectedSlot = 0; skillArmed = false; lastPhase = ''; scenery(); game.camera.position.set(0, 35, 27); render(.04); game.ui.hideOverlay(); }
function menu() { game.ui.overlay({ title: '在掌心，守一座城。', text: '三十道防线 · 八种元素塔 · 十六条升级分支', body: `<p class="battle-note">一条弯路，是一秒喘息。<br>把金币花在敌人会经过的地方。</p><div class="field"><label for="level-choice">防线</label><select id="level-choice">${Array.from({ length: 30 }, (_, i) => `<option value="${i}" ${i === selectedLevel ? 'selected' : ''}>${String(i + 1).padStart(2, '0')} ${levelConfig(i).name} ${'★'.repeat(save.stars[i])}</option>`).join('')}</select></div><p class="muted" id="battle-rule">${levelConfig(selectedLevel).rule}</p><div class="field"><label for="challenge-choice">挑战条件</label><select id="challenge-choice"><option value="standard">常规守线 · 20 生命</option><option value="iron">铁壁挑战 · 一次失守即失败</option><option value="rush">急行军 · 敌军快 35%</option></select></div><p class="muted">军功 ${save.tokens} · 火力研究 ${save.power}/10 · 后勤研究 ${save.economy}/8 · 总星数 ${save.stars.reduce((a, b) => a + b, 0)}/90</p>`, buttons: [{ label: '布置防线', primary: true, onClick: () => { selectedLevel = Number(document.querySelector('#level-choice').value); challenge = document.querySelector('#challenge-choice').value; start(); } }, ...(state && ['build', 'wave'].includes(state.phase) ? [{ label: '继续本局', onClick: () => { selectedLevel = state.config.index; challenge = state.challenge; game.ui.hideOverlay(); } }] : []), { label: '军功研究', onClick: researchMenu }, { label: '元素手册', onClick: guideMenu }] }); document.querySelector('#challenge-choice').value = challenge; document.querySelector('#level-choice').addEventListener('change', e => { selectedLevel = Number(e.target.value); document.querySelector('#battle-rule').textContent = levelConfig(selectedLevel).rule; }); }
function buildMenu() {
  if (!['build', 'wave'].includes(state.phase)) return; const tower = state.towers.find(t => t.slot === selectedSlot);
  if (!tower) { game.ui.overlay({ title: `基座 ${String(selectedSlot + 1).padStart(2, '0')} · 建造`, text: `可用金币 ${state.gold}。点击塔卡建造；选择期间战场暂停。`, body: `<div class="choice-grid tower-grid">${TOWERS.map(t => `<button class="choice tower-option" data-tower="${t.id}" ${state.gold < t.cost ? 'disabled' : ''}><strong>${t.name}<em>${t.cost}</em></strong><small>${t.desc}<br>伤害 ${t.damage} · 射程 ${t.range}</small></button>`).join('')}</div>`, buttons: [{ label: '返回战场', onClick: () => game.ui.hideOverlay() }] }); document.querySelectorAll('[data-tower]').forEach(button => button.addEventListener('click', () => { if (buildTower(state, selectedSlot, button.dataset.tower)) { game.ui.hideOverlay(); render(.016); } else game.ui.toast('金币不足或这个基座已经有塔。'); })); }
  else { const def = TOWERS.find(x => x.id === tower.type), stat = towerStats(tower, state), cost = upgradeCost(tower); game.ui.overlay({ title: `${def.name} · ${tower.level} 级`, text: `伤害 ${Math.round(stat.damage)} · 射程 ${stat.range.toFixed(1)} · 攻击间隔 ${stat.rate.toFixed(2)}s\n当前金币 ${state.gold} · 投入 ${tower.spent}`, body: tower.level === 2 ? `<p class="section-label">永久选择升级分支 · ${cost} 金币</p><div class="choice-grid">${def.branches.map(b => `<button class="choice" data-branch="${b.id}" ${state.gold < cost ? 'disabled' : ''}><strong>${b.name}</strong><small>${b.desc}</small></button>`).join('')}</div>` : `<p class="muted">${tower.branch ? '已选择：' + def.branches.find(b => b.id === tower.branch).name : '先升至二级，再选择一种专精分支。'}</p>`, buttons: [...(tower.level === 1 ? [{ label: `升至二级 · ${cost}`, primary: true, disabled: state.gold < cost, onClick: () => { if (upgradeTower(state, selectedSlot)) buildMenu(); } }] : []), { label: `回收 · ${Math.floor(tower.spent * .7)}`, onClick: () => { sellTower(state, selectedSlot); game.ui.hideOverlay(); } }, { label: '返回战场', onClick: () => game.ui.hideOverlay() }] }); document.querySelectorAll('[data-branch]').forEach(button => button.addEventListener('click', () => { if (upgradeTower(state, selectedSlot, button.dataset.branch)) game.ui.hideOverlay(); })); }
}
function researchMenu() { game.ui.overlay({ title: '军功研究', text: `军功 ${save.tokens}。新获得的星级带来军功，每次胜利也会获得奖励。`, body: `<div class="choice-grid"><div class="choice"><strong>火力 ${save.power}/10</strong><small>每级增加 2.5% 全塔伤害</small></div><div class="choice"><strong>后勤 ${save.economy}/8</strong><small>每级增加 12 起始金币</small></div></div>`, buttons: [{ label: `研究火力 · ${20 + save.power * 15}`, disabled: save.power >= 10, onClick: () => research('power') }, { label: `研究后勤 · ${20 + save.economy * 15}`, disabled: save.economy >= 8, onClick: () => research('economy') }, { label: '返回', onClick: menu }] }); }
function research(key) { const next = buyResearch(save, key); if (!next) game.ui.toast('军功不足，继续守线获取星级。'); else { save = next; game.save(save); researchMenu(); } }
function guideMenu() { game.ui.overlay({ title: '元素与战术', text: '克制造成 160% 伤害，抗性降为 55%。物理攻击受护甲影响，光系无视护甲。', body: `<div class="element-guide"><p><b>元素克制</b><br>火 → 木 · 水 → 火 · 雷 → 水<br>木 → 水 · 冰 → 火 · 光 → 暗</p><p><b>联合防御</b><br>潮湿 + 雷电：额外 50% 伤害<br>潮湿 + 冰川分支：冻结目标</p><p><b>目标选择</b><br>大多数塔优先接近城门的敌军。<br>猎鹰与破城分支优先高生命目标。</p><p><b>敌军行为</b><br>复苏先知治疗附近友军；影翼移动快。<br>铁甲兽抗物理；巨兽失守扣 5 生命。</p></div><p class="section-label">八塔专精</p><div class="choice-grid">${TOWERS.map(t => `<div class="choice"><strong>${t.name}</strong><small>${t.branches.map(b => b.name + '：' + b.desc).join('<br>')}</small></div>`).join('')}</div>`, buttons: [{ label: '返回', primary: true, onClick: menu }] }); }
function toggleSkill() { if (state.phase !== 'wave') { game.ui.toast('敌军进场后才能释放流星。'); return; } if (state.skillCooldown > 0) { game.ui.toast(`流星还需 ${Math.ceil(state.skillCooldown)} 秒恢复。`); return; } skillArmed = !skillArmed; }
function launchWave() { if (startWave(state)) { game.sound(240, .3, 'triangle'); game.ui.toast(`第 ${state.wave} 波来袭`); } }
function finish() { const before = save.tokens; save = settleBattle(state, save); game.save(save); game.ui.overlay({ title: state.phase === 'won' ? '城门依旧屹立。' : '防线失守，重新布阵。', text: `${state.config.name}\n击退 ${state.kills} · 剩余生命 ${state.lives} · 获得军功 ${save.tokens - before}`, body: `<p class="battle-note">${state.phase === 'won' ? '★'.repeat(save.stars[state.config.index]) + ' · 越少失守，星级越高。' : '在回折处集中火力，用水与雷的配合消灭重甲群。流星能解救突破中的城门。'}</p>`, buttons: [...(state.phase === 'won' && selectedLevel < 29 ? [{ label: '下一道防线', primary: true, onClick: () => { selectedLevel++; start(); } }] : []), { label: '重布本关', onClick: start }, { label: '关卡选择', onClick: menu }] }); }
dock.querySelector('#pad-select').addEventListener('change', e => { setSlot(Number(e.target.value)); buildMenu(); }); dock.querySelector('.build-button').addEventListener('click', buildMenu); dock.querySelector('.wave-button').addEventListener('click', launchWave); dock.querySelector('.meteor-button').addEventListener('click', toggleSkill);
game.onMenu(menu); state = createBattle(); scenery(); game.camera.position.set(0, 36, 28); render(.1); menu();
game.run(dt => {
  if (game.input.pressed('ArrowLeft') || game.input.pressed('KeyA') || game.input.pressed('ArrowUp') || game.input.pressed('KeyW')) setSlot(selectedSlot - 1);
  if (game.input.pressed('ArrowRight') || game.input.pressed('KeyD') || game.input.pressed('ArrowDown') || game.input.pressed('KeyS')) setSlot(selectedSlot + 1);
  ray.setFromCamera(game.input.pointer, game.camera); if (ray.ray.intersectPlane(ground, hitPoint)) pointerWorld = { x: Math.max(-14, Math.min(14, hitPoint.x)), z: Math.max(-10, Math.min(10, hitPoint.z)) };
  if (game.input.pressed('KeyE')) toggleSkill(); if (game.input.pressed('KeyN')) launchWave();
  if (game.input.pressed('Space')) { if (skillArmed) { const target = state.enemies.slice().sort((a, b) => b.distance - a.distance)[0]; if (target) { castSkill(state, target.x, target.z); skillArmed = false; } } else { buildMenu(); return; } }
  if (game.input.pointer.tap) { if (skillArmed) { castSkill(state, pointerWorld.x, pointerWorld.z); skillArmed = false; } else { let nearest = -1, min = 1.65; state.config.pads.forEach((p, i) => { const d = Math.hypot(p.x - pointerWorld.x, p.z - pointerWorld.z); if (d < min) { min = d; nearest = i; } }); if (nearest >= 0) { setSlot(nearest); buildMenu(); return; } } }
  stepBattle(state, dt); render(dt);
  for (const event of state.events) { if (event.type === 'leak') game.sound(110, .2, 'triangle'); if (event.type === 'clear') game.ui.toast(`防线稳固 · 补给 +${event.bonus} 金币`); if (event.type === 'skill') game.sound(100, .35, 'sawtooth', .04); if (event.type === 'fire' && state.time - lastSound > .18) { game.sound(340, .05, 'triangle', .014); lastSound = state.time; } }
  if (lastPhase !== state.phase) { lastPhase = state.phase; if (state.phase === 'won' || state.phase === 'lost') finish(); }
});
