import {THREE,createGame,box,sphere,cylinder,label,clearGroup} from '../arcade-runtime/runtime.mjs';
import {TIERS,MODES,MISSIONS,createFoundry,stepFoundry,dropBall,shakeFoundry,swapNext,missionProgress,validateSave} from './core.mjs';
const game=createGame({id:'jelly-foundry',title:'果冻合成工坊',subtitle:'JELLY FOUNDRY / SMALL BATCH',accent:'#e8bfd7',background:0x29383c,help:'鼠标左右移动瞄准，点击容器或空格投放。A / D 或方向键也可调整。相同等级果冻碰到后会合成，异级果冻会真实堆叠。E 震动容器（12秒冷却），Q 交换下一颗（每局3次）。顶部虚线以上持续2秒会失败。R 重开，P 暂停。'});
game.controls([{code:'Space',label:'投放'},{code:'KeyE',label:'震动'},{code:'KeyQ',label:'交换'}]);
let save=validateSave(game.load({})),mode='classic',mission=0,group=0,state=null,ended=false,nozzle,preview,nextPreview,floorMesh,guide,gears=[],balls=new Map(),particles=[],lastNext=-1,lastAfter=-1,lastPointerX=999;
const factory=new THREE.Group(),contents=new THREE.Group(),effects=new THREE.Group();[factory,contents,effects].forEach(g=>game.world.add(g));
const live=document.createElement('aside');live.className='jelly-live';live.hidden=true;document.body.append(live);
const ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,0,1),0),hit=new THREE.Vector3();
function torus(parent,x,y,z,r,t,color,rotation=0){const m=new THREE.Mesh(new THREE.TorusGeometry(r,t,8,28),new THREE.MeshStandardMaterial({color,roughness:.4,metalness:.25}));m.position.set(x,y,z);m.rotation.x=rotation;parent.add(m);return m;}
function jellyModel(level){const tier=TIERS[level],r=tier.radius,g=new THREE.Group();
  const body=sphere(g,0,0,0,r,tier.color,{roughness:.18,metalness:.08,segments:24});body.scale.z=.85;
  const gleam=sphere(g,-r*.34,r*.35,r*.65,r*.18,0xffffff,{opacity:.65,roughness:.05});gleam.scale.set(1,.52,.18);
  for(const x of [-1,1]){const eye=sphere(g,x*r*.27,r*.04,r*.82,r*.074,0x3c3b4b);eye.scale.z=.5;sphere(g,x*r*.29,r*.07,r*.855,r*.024,0xffffff);const cheek=sphere(g,x*r*.45,-r*.12,r*.73,r*.11,0xf9a7b4,{opacity:.5});cheek.scale.set(1,.4,.15);}
  const smile=torus(g,0,-r*.15,r*.83,r*.12,r*.026,0x645063);smile.scale.y=.6;smile.rotation.z=Math.PI;
  if(level%3===1){const leaf=sphere(g,-r*.12,r*.91,0,r*.26,0x71a591);leaf.scale.set(.45,1.2,.32);leaf.rotation.z=-.6;cylinder(g,0,r*1.04,0,r*.03,r*.04,r*.2,0x84705e);}
  if(level%3===2){for(let i=0;i<3;i++){const berry=sphere(g,(i-1)*r*.23,r*.86+Math.sin(i)*r*.08,-.02,r*.16,0xd781ad);sphere(g,(i-1)*r*.23,r*1.02+Math.sin(i)*r*.08,-.02,r*.06,0x8a7896);}}
  if(level>=4){const ring=torus(g,0,-r*.25,0,r*.9,r*.025,0xffffff,Math.PI/2);ring.material.transparent=true;ring.material.opacity=.32;}
  if(level>=8){for(const side of [-1,1]){const wing=sphere(g,side*r*.85,r*.15,0,r*.28,0xf9dfdc);wing.scale.set(1.2,.6,.22);wing.rotation.z=side*.5;}}
  if(level>=10){cylinder(g,0,r*.95,0,r*.43,r*.4,r*.22,0xf1d58f);for(let i=0;i<5;i++){const a=i/5*Math.PI*2;cylinder(g,Math.cos(a)*r*.34,r*1.17,Math.sin(a)*r*.34,0,r*.12,r*.4,0xf2d68e);sphere(g,Math.cos(a)*r*.34,r*1.39,Math.sin(a)*r*.34,r*.06,0xffefd3);}}
  return g;
}
function buildFactory(){clearGroup(factory);clearGroup(contents);clearGroup(effects);balls.clear();particles=[];gears=[];lastNext=-1;lastAfter=-1;preview=null;nextPreview=null;
  const w=state?.width||3.8;
  box(factory,0,-.65,0,18,.6,10,0x718489,{roughness:.8});box(factory,0,-.26,0,11.1,.34,4.4,0xa69b94);box(factory,0,-.05,0,9,.2,3.35,0xe0c9ad);
  floorMesh=box(factory,0,.2,0,w*2+.1,.32,2.7,0x788c85,{metalness:.3});box(factory,0,.4,-1.2,w*2,.06,.15,0xc8c5b2);
  for(const side of [-1,1]){box(factory,side*(w+.1),4.3,0,.2,8.8,2.8,0xb5cfc9,{opacity:.23,roughness:.1,metalness:.1});cylinder(factory,side*(w+.22),4.5,-1.25,.1,.13,9,0xcdb793);cylinder(factory,side*(w+.22),4.5,1.25,.1,.13,9,0xcdb793);sphere(factory,side*(w+.22),9,-1.25,.17,0xe8d6ac);}
  box(factory,0,4.5,-1.3,w*2,8.5,.08,0xb1d6d1,{opacity:.07,roughness:.1});
  for(let i=0;i<16;i++)box(factory,-w+i*(w*2/16)+.15,8.2,1.28,.24,.025,.025,0xe999a4,{emissive:0xa34451});
  box(factory,0,9.2,-.9,w*2+.6,.32,.45,0x93b5ae);box(factory,0,9.2,-.63,w*2,.06,.03,0xecd5b0,{emissive:0x766a48});
  nozzle=new THREE.Group();nozzle.position.y=9.3;cylinder(nozzle,0,0,0,.52,.35,.55,0xccbca6,{metalness:.5});cylinder(nozzle,0,-.38,0,.34,.48,.25,0xe4cbb0);torus(nozzle,0,-.52,0,.34,.05,0xd9b58e,Math.PI/2);factory.add(nozzle);
  const machine=new THREE.Group();machine.position.set(-5.9,0,-.5);box(machine,0,1.4,0,2.1,3,2.2,0x789c97);box(machine,0,2.5,1.12,1.7,.45,.06,0x445e64);label(machine,'SMALL BATCH',0,2.53,1.2,{size:.22,color:'#e2d8bf'});for(let i=0;i<3;i++){cylinder(machine,(i-1)*.5,1.5,1.2,.09,.09,.1,[0xefb3a9,0xe5d093,0xa1cfc3][i],{rotation:[Math.PI/2,0,0]});}
  for(let i=0;i<2;i++){const g=new THREE.Group();g.position.set((i-.5)*.85,.65,1.15);torus(g,0,0,0,.36,.085,0xcdba9f);for(let n=0;n<8;n++){const tooth=box(g,Math.sin(n*Math.PI/4)*.37,Math.cos(n*Math.PI/4)*.37,0,.13,.16,.13,0xc1ad92);tooth.rotation.z=-n*Math.PI/4;}cylinder(g,0,0,.06,.09,.09,.1,0x6e7c77,{rotation:[Math.PI/2,0,0]});machine.add(g);gears.push(g);}factory.add(machine);
  const hopper=cylinder(factory,-5.9,4.6,-.5,.95,.3,2.6,0xabc9c1,{opacity:.3,roughness:.2});for(let i=0;i<7;i++)sphere(factory,-5.9+Math.sin(i*3)*.45,3.7+i*.26,-.5+Math.cos(i*2)*.3,.24,TIERS[i%4].color);
  cylinder(factory,5.5,2.2,0,.65,.85,4.4,0x87a5a0);torus(factory,5.5,4.2,0,.66,.1,0xd6b892,Math.PI/2);box(factory,5.5,4.65,0,1.3,.8,.9,0xb9c9b7);label(factory,'NEXT',5.5,6.15,0,{size:.34,color:'#eadcbe'});
  for(let i=0;i<5;i++){const jar=new THREE.Group();jar.position.set(-7+i*3.3,.2,-3.8);cylinder(jar,0,.65,0,.45,.42,1.2,0xc2ddd1,{opacity:.25});cylinder(jar,0,1.3,0,.47,.47,.13,0xbaac91);sphere(jar,0,.6,0,.3,TIERS[(i+4)%12].color);factory.add(jar);}
  box(factory,0,10.5,-3,13,.12,.7,0x8eaa9e);for(const x of [-5,0,5]){cylinder(factory,x,10,-2.5,.03,.03,1,0xd9d0b6);cylinder(factory,x,9.4,-2.5,.28,.7,.42,0xe0cdb0);sphere(factory,x,9.2,-2.5,.25,0xffe3b5,{emissive:0xc48c4b});}
  label(factory,'THE JELLY FOUNDRY',0,11.5,-2.2,{size:.7,color:'#e6d4b5'});
  if(state)for(const p of state.pegs){cylinder(factory,p.x,p.y,0,p.radius,p.radius,2.6,0xb7a890,{rotation:[Math.PI/2,0,0],metalness:.6});torus(factory,p.x,p.y,1.35,p.radius*.72,.07,0xd9c6a7);}
  const lineGeometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,8,0),new THREE.Vector3(0,.5,0)]);guide=new THREE.Line(lineGeometry,new THREE.LineDashedMaterial({color:0xffeed5,transparent:true,opacity:.5,dashSize:.13,gapSize:.13}));guide.computeLineDistances();factory.add(guide);
  fitCamera();
}
function fitCamera(){const ratio=innerWidth/innerHeight;const distance=ratio<.8?22:17;game.camera.fov=48;game.camera.position.set(ratio<.8?0:1.2,6.8,distance);game.camera.lookAt(0,4.7,0);game.camera.updateProjectionMatrix();}
window.addEventListener('resize',fitCamera);
function targetText(task){return task.goal==='level'?`合成 ${TIERS[task.target].name}（${task.target+1} 级）`:task.goal==='merges'?`完成 ${task.target} 次合并`:`取得 ${task.target} 分`;}
function showMenu(){live.hidden=true;game.ui.overlay({title:'今天，调一罐甜。',text:'圆滚滚的果冻在玻璃容器里碰撞、挤压与相遇。瞄准落点，让两颗相同果冻合成新的味道。',body:`<div class="choice-grid">${MODES.map(m=>`<button class="choice ${mode===m.id?'selected':''}" data-mode="${m.id}"><strong>${m.name}</strong><small>${m.description}</small></button>`).join('')}</div>${mode==='missions'?`<div class="field"><label for="batch-select">容器批次</label><select id="batch-select">${['原味宽罐','黄铜分流器','缓升活塞罐'].map((n,i)=>`<option value="${i}" ${i===group?'selected':''}>${i+1} · ${n}</option>`).join('')}</select></div><div class="mission-grid">${MISSIONS.filter(m=>Math.floor(m.id/10)===group).map(m=>`<button data-mission="${m.id}" class="${m.id===mission?'selected':''}" ${m.id>=save.unlocked?'disabled':''}>${String(m.id+1).padStart(2,'0')}<small>${m.id<save.unlocked?(save.medals[m.id]?'★'.repeat(save.medals[m.id]):'待试产'):'待解锁'}</small></button>`).join('')}</div><p class="muted">订单 ${mission+1} · ${MISSIONS[mission].name}：${targetText(MISSIONS[mission])}，限 ${MISSIONS[mission].drops} 次投料。</p>`:''}<p class="section-label">十二味合成链 · 已发现 ${TIERS[save.maxLevel].name}</p><div class="jelly-chain">${TIERS.map(t=>`<i title="${t.name}" data-tier="${t.id+1}" style="background:#${t.color.toString(16)}"></i>`).join('')}</div><p class="muted">悠闲纪录 ${save.best} 分 · 快线纪录 ${save.timedBest} 分<br>交换配料每局 3 次；机器震动冷却 12 秒。进度仅保存在此浏览器。</p>`,buttons:[{label:mode==='missions'?'开始这份订单':'开动工坊',primary:true,disabled:mode==='missions'&&mission>=save.unlocked,onClick:()=>start(mode,mission)},{label:'继续当前',disabled:!state||state.status!=='running',onClick:()=>{mode=state.mode;mission=state.mission.id;live.hidden=false;game.ui.hideOverlay();}}]});
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;showMenu();});document.querySelector('#batch-select')?.addEventListener('change',e=>{group=Number(e.target.value);mission=group*10;showMenu();});document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{mission=Number(b.dataset.mission);showMenu();});
}
function start(m=mode,n=mission){mode=m;mission=n;state=createFoundry({mode:m,mission:n});ended=false;buildFactory();game.ui.hideOverlay();live.hidden=false;lastPointerX=game.input.pointer.x;game.ui.hint('点容器投放 · A/D 调整 · E 震动 · Q 交换 · R 重开');}
function finish(){ended=true;save.maxLevel=Math.max(save.maxLevel,state.maxLevel);if(state.mode==='classic')save.best=Math.max(save.best,state.score);if(state.mode==='timed')save.timedBest=Math.max(save.timedBest,state.score);if(state.mode==='missions'&&state.status==='won'){const medals=1+(state.drops<state.mission.drops*.7?1:0)+(state.overflow===0?1:0);save.medals[state.mission.id]=Math.max(save.medals[state.mission.id],medals);save.unlocked=Math.max(save.unlocked,Math.min(30,state.mission.id+2));}game.save(save);live.hidden=true;game.ui.overlay({title:state.status==='won'?'这一罐，恰到好处。':'工坊打烊啦',text:state.status==='won'?'订单已经完成，收好这份新配方。':state.mode==='timed'?'90 秒结束。500 分即可完成快线挑战。':state.overflow>=2?'果冻堆过了安全线。下一罐试着分散落点，留出合并空间。':'投料次数已用完，合成目标尚未完成。',body:`<div class="choice-grid"><div class="choice"><strong>${state.score} 分</strong><small>${state.merges} 次合并</small></div><div class="choice"><strong>${TIERS[state.maxLevel].name}</strong><small>本罐最高 ${state.maxLevel+1} 级</small></div><div class="choice"><strong>${state.drops} 次</strong><small>使用配料</small></div></div>`,buttons:[...(state.status==='won'&&state.mode==='missions'&&state.mission.id<29?[{label:'下一份订单',primary:true,onClick:()=>start('missions',state.mission.id+1)}]:[]),{label:'再调一罐',primary:state.status!=='won',onClick:()=>start(state.mode,state.mission.id)},{label:'返回工坊',onClick:showMenu}]});}
function particle(x,y,color){for(let i=0;i<12;i++){const m=sphere(effects,x,y,.5,.04+Math.random()*.07,color,{roughness:.2});particles.push({m,v:new THREE.Vector3((Math.random()-.5)*4,Math.random()*4,(Math.random()-.5)*3),life:.7});}}
game.onMenu(showMenu);
game.run((dt,time)=>{if(!state)return;if(game.input.pressed('KeyR')){start(state.mode,state.mission.id);return;}const pointer=game.input.pointer;if(pointer.x!==lastPointerX||pointer.tap){ray.setFromCamera(new THREE.Vector2(pointer.x,pointer.y),game.camera);if(ray.ray.intersectPlane(plane,hit))state.aim=Math.max(-state.width+TIERS[state.next].radius,Math.min(state.width-TIERS[state.next].radius,hit.x));lastPointerX=pointer.x;}
  state.aim=Math.max(-state.width+TIERS[state.next].radius,Math.min(state.width-TIERS[state.next].radius,state.aim+game.input.axis('x')*dt*5));
  if((pointer.tap&&Math.abs(hit.x)<state.width+.3&&hit.y>-.2&&hit.y<10)||game.input.pressed('Space')){if(dropBall(state,state.aim))game.sound(280,.07,'sine');}
  if(game.input.pressed('KeyE')){if(shakeFoundry(state)){game.sound(105,.2,'triangle');game.ui.toast('轻轻摇匀，看看谁会相遇。');}else game.ui.toast(`震动冷却还剩 ${Math.ceil(state.shake)} 秒`);}
  if(game.input.pressed('KeyQ')){if(!swapNext(state))game.ui.toast('本罐的交换次数已用完。');}
  stepFoundry(state,dt);floorMesh.position.y=state.floor-.1;nozzle.position.x=state.aim;nozzle.rotation.z=state.shakeTimer>0?Math.sin(time*30)*.02:0;
  if(state.next!==lastNext){if(preview){clearGroup(preview);factory.remove(preview);}preview=jellyModel(state.next);preview.scale.setScalar(.72);factory.add(preview);lastNext=state.next;}preview.position.set(state.aim,8.7,0);preview.visible=state.cooldown<.25;preview.rotation.y=Math.sin(time)*.08;
  if(state.after!==lastAfter){if(nextPreview){clearGroup(nextPreview);factory.remove(nextPreview);}nextPreview=jellyModel(state.after);nextPreview.scale.setScalar(.75);nextPreview.position.set(5.5,5.45,0);factory.add(nextPreview);lastAfter=state.after;}
  let landing=state.floor;for(const b of state.balls)if(Math.abs(b.x-state.aim)<b.radius+TIERS[state.next].radius*.65)landing=Math.max(landing,b.y+b.radius);const pos=guide.geometry.attributes.position;pos.setXYZ(0,state.aim,8.2,.03);pos.setXYZ(1,state.aim,Math.min(8,landing+.08),.03);pos.needsUpdate=true;guide.computeLineDistances();
  const activeIds=new Set(state.balls.map(b=>b.id));for(const[id,m]of balls)if(!activeIds.has(id)){clearGroup(m);contents.remove(m);balls.delete(id);}for(const b of state.balls){let m=balls.get(b.id);if(!m){m=jellyModel(b.level);contents.add(m);balls.set(b.id,m);}m.position.set(b.x,b.y,Math.sin(b.id*2.1)*.07);const squash=Math.min(.1,Math.abs(b.vy)*.008);m.scale.set(1-squash*.3,1+squash,1-squash*.3);m.rotation.z=Math.max(-.25,Math.min(.25,-b.vx*.04));}
  for(const e of state.events)if(e.type==='merge'){particle(e.x,e.y,TIERS[e.level].color);game.sound(340+e.level*70,.14,'sine');}
  for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.v.y-=5*dt;p.m.scale.setScalar(Math.max(.01,p.life));if(p.life<=0){p.m.geometry.dispose();p.m.material.dispose();effects.remove(p.m);particles.splice(i,1);}}
  gears.forEach((g,i)=>g.rotation.z=time*(i?-.4:.4));
  game.ui.stats([{label:'甜度得分',value:state.score},{label:'最高果冻',value:`${state.maxLevel+1} 级`},{label:state.mode==='timed'?'剩余时间':'投料',value:state.mode==='timed'?`${Math.ceil(state.time)} s`:state.mode==='missions'?`${state.drops}/${state.mission.drops}`:state.drops},{label:'安全线',value:state.overflow>.1?'注意堆高':'余量充足'}]);
  live.innerHTML=`<small>${state.mode==='missions'?`订单 ${state.mission.id+1} / 30`:'本罐配料'}</small><strong>下一颗 · ${TIERS[state.next].name}</strong><p>${state.mode==='missions'?targetText(state.mission)+`<br>进度 ${state.mission.goal==='level'?state.maxLevel+1:missionProgress(state)} / ${state.mission.goal==='level'?state.mission.target+1:state.mission.target}`:state.mode==='timed'?'目标：90 秒内取得 500 分':'相同果冻接触，合成下一味。'}<br>震动 ${state.shake>0?Math.ceil(state.shake)+' s':'就绪'} · 交换 ${state.swaps}</p>`;
  if(state.status!=='running'&&!ended)finish();
});
buildFactory();showMenu();
