import {THREE,createGame,box,sphere,cylinder,label,clearGroup} from '../arcade-runtime/runtime.mjs';
import {ISLANDS,LEVELS,createPuzzle,actPuzzle,undoPuzzle,traceLight,gateOpen,solveLevel,validateSave} from './core.mjs';
const game=createGame({id:'mechanism-isles',title:'机关小岛',subtitle:'MECHANISM ISLES / LITTLE DISCOVERIES',accent:'#bad5bb',background:0x294851,help:'方向键 / WASD 移动。木箱只能推动，推上圆形压板可开门。靠近镜座或水阀后按空格操作：转镜接通光线、切换水位让石路或浮桥可通行。Q / E 旋转镜头，Z 撤销，H 获取真实可执行提示，R 重开。收集两颗星屑并尽量不用提示可得三星。推箱进入死角会提示失败，可撤销恢复。'});
game.controls([{code:'Space',label:'操作'},{code:'KeyZ',label:'撤销'},{code:'KeyH',label:'提示'},{code:'KeyE',label:'转视角'}]);
let save=validateSave(game.load({})),selected=Math.min(47,save.unlocked-1),island=Math.floor(selected/8),state=null,ended=false,turn=0,angle=Math.PI/4,angleTarget=Math.PI/4,wait=0,hints=0,avatar,avatarLegs=[],crateMeshes=[],mirrorMeshes=[],waterMeshes=[],bridgeMeshes=[],stars=[],valveMeshes=[],gateMesh,gateY=0,beamKey='',tiles=[],trees=[],decorMotions=[];
const terrain=new THREE.Group(),mechanisms=new THREE.Group(),actors=new THREE.Group(),beam=new THREE.Group(),backdrop=new THREE.Group();[terrain,mechanisms,actors,beam,backdrop].forEach(g=>game.world.add(g));
const note=document.createElement('aside');note.className='island-note';note.hidden=true;document.body.append(note);const ray=new THREE.Raycaster();
const cell=p=>new THREE.Vector3((p.x-4)*1.3,.48,(p.y-4)*1.3),point=(x,y,z)=>new THREE.Vector3(x,y,z);
function torus(parent,x,y,z,r,t,color,rx=0){const m=new THREE.Mesh(new THREE.TorusGeometry(r,t,8,28),new THREE.MeshStandardMaterial({color,roughness:.45,metalness:.3}));m.position.set(x,y,z);m.rotation.x=rx;parent.add(m);return m;}
function crystal(parent,x,y,z,r,color){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(r,0),new THREE.MeshStandardMaterial({color,roughness:.15,metalness:.25,emissive:color,emissiveIntensity:.2}));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
function tube(parent,a,b,r,color,glow=false){const delta=b.clone().sub(a),length=delta.length();const m=cylinder(parent,(a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2,r,r,length,color,glow?{emissive:color,emissiveIntensity:1.2}:{metalness:.5});m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());return m;}
function explorer(){const g=new THREE.Group();cylinder(g,0,.43,0,.2,.26,.47,0xb4c8b1);box(g,0,.48,.19,.35,.4,.19,0xb69272);box(g,0,.52,.3,.27,.08,.06,0xd3b28b);sphere(g,0,.91,0,.235,0xe5c4a4);for(const x of [-.08,.08])sphere(g,x,.94,-.21,.023,0x46514e);const hair=sphere(g,0,1.03,.05,.24,0x625b50);hair.scale.y=.54;cylinder(g,0,1.11,0,.26,.29,.16,0xd8cda8);cylinder(g,0,1.055,-.03,.36,.36,.04,0xc7b994);box(g,.2,1.12,.03,.07,.14,.12,0xb79a70);
  avatarLegs=[];for(const side of [-1,1]){const leg=new THREE.Group();leg.position.set(side*.12,.24,0);cylinder(leg,0,-.1,0,.065,.067,.22,0x6c7b74);box(leg,0,-.22,-.055,.14,.09,.23,0x6d5d50);g.add(leg);avatarLegs.push(leg);const arm=cylinder(g,side*.26,.44,0,.066,.06,.32,0xb7c8ab);arm.rotation.z=side*.16;sphere(g,side*.29,.25,0,.066,0xe2bd9d);}return g;}
function crateModel(){const g=new THREE.Group();box(g,0,.38,0,.9,.76,.9,0xae8864,{roughness:.9});for(const x of [-.37,.37])for(const z of [-.37,.37])box(g,x,.39,z,.11,.82,.11,0xd7b88b);for(const y of [.06,.71]){box(g,0,y,.46,.92,.11,.06,0x715f4d);box(g,0,y,-.46,.92,.11,.06,0x715f4d);box(g,.46,y,0,.06,.11,.92,0x715f4d);box(g,-.46,y,0,.06,.11,.92,0x715f4d);}for(let i=-1;i<=1;i++)box(g,i*.27,.787,0,.018,.02,.82,0x806a51);const brace=box(g,0,.38,.48,.1,.85,.045,0xe0bc85);brace.rotation.z=.75;return g;}
function mirrorModel(){const g=new THREE.Group();cylinder(g,0,.15,0,.37,.43,.27,0xbda687);cylinder(g,0,.48,0,.07,.11,.58,0x9c8c71);const head=new THREE.Group();head.position.y=.9;box(head,0,0,0,.79,.67,.11,0x839e9c,{metalness:.95,roughness:.06});for(const x of [-.43,.43])box(head,x,0,0,.07,.78,.15,0xdcc6a3);for(const y of [-.36,.36])box(head,0,y,0,.93,.06,.15,0xdcc6a3);box(head,0,.02,-.07,.63,.025,.012,0xf2f8df,{emissive:0xb8d9c8});g.add(head);g.userData.head=head;return g;}
function valveModel(){const g=new THREE.Group();cylinder(g,0,.25,0,.28,.38,.4,0x8caaa4);cylinder(g,0,.65,0,.07,.11,.5,0xc0b08c);const wheel=new THREE.Group();wheel.position.set(0,.97,0);torus(wheel,0,0,0,.32,.045,0xd4ab80);for(let i=0;i<4;i++){const spoke=box(wheel,0,0,0,.61,.035,.04,0xd4ab80);spoke.rotation.z=i*Math.PI/4;}sphere(wheel,0,0,.02,.07,0x778d84);g.add(wheel);g.userData.wheel=wheel;return g;}
function tree(parent,x,z,kind=0){const g=new THREE.Group();g.position.set(x,0,z);if(kind===0||kind===4){cylinder(g,0,.8,0,.12,.23,1.6,0x8b8170);for(let n=0;n<3;n++){const crown=sphere(g,Math.sin(n*3)*.34,1.8+n*.24,Math.cos(n*3)*.25,.7,kind===4?0x608c80:0x8eae8c);crown.scale.set(.9,1.12,.9);}}else if(kind===1){crystal(g,0,1,0,.65,0xd4b47a).scale.y=2;for(const x of [-.5,.5])crystal(g,x,.45,.1,.27,0xc0b196).scale.y=1.7;}else if(kind===2){cylinder(g,0,.5,0,.15,.22,1,0xa3a185);torus(g,0,1.07,0,.33,.08,0xe1b086,Math.PI/2);sphere(g,0,1.24,0,.1,0xe6dab7,{emissive:0xc7ab6e});}else if(kind===3){cylinder(g,0,.8,0,.35,.45,1.6,0x8f9b90);const wheel=torus(g,0,1.75,0,.65,.12,0xbba985);for(let n=0;n<10;n++){const tooth=box(g,Math.sin(n*.628)*.66,1.75+Math.cos(n*.628)*.66,0,.18,.18,.17,0xbba985);tooth.rotation.z=-n*.628;}decorMotions.push(wheel);}else{cylinder(g,0,.8,0,.14,.28,1.6,0xa2aca3);const telescope=cylinder(g,0,1.6,0,.25,.18,1.3,0xc1b4ca,{rotation:[Math.PI/3,0,0],metalness:.5});torus(g,0,2.1,-.5,.3,.07,0xceb88f,Math.PI/3);crystal(g,.5,.6,.2,.16,0xd5c6de);}parent.add(g);trees.push(g);}
function buildIsland(l){[terrain,mechanisms,actors,beam,backdrop].forEach(clearGroup);crateMeshes=[];mirrorMeshes=[];waterMeshes=[];bridgeMeshes=[];stars=[];valveMeshes=[];tiles=[];trees=[];decorMotions=[];beamKey='';const theme=ISLANDS[l.island];
  game.scene.background.set([0x3c6064,0x615d55,0x355c6b,0x515657,0x335e5c,0x454c68][l.island]);game.scene.fog.color.copy(game.scene.background);game.scene.fog.near=38;game.scene.fog.far=95;
  box(backdrop,0,-1.9,0,130,.1,130,l.island===5?0x68758a:0x5c8d92,{metalness:.3,roughness:.24});
  for(let i=0;i<18;i++){const a=i*2.4,r=9+(i%3)*3;const foam=torus(backdrop,Math.sin(a)*r,-1.82,Math.cos(a)*r,1+(i%3)*.5,.014,0x93b7b2,Math.PI/2);foam.scale.x=2;decorMotions.push(foam);}
  for(let y=0;y<9;y++)for(let x=0;x<9;x++){const type=l.tiles[y][x],p=cell({x,y});if(type==='#'){if(x>0&&x<8&&y>0&&y<8){const rock=box(terrain,p.x,.77,p.z,1.24,1.2,1.24,0x899289);box(terrain,p.x,1.4,p.z,1.32,.14,1.32,0xa2ad9a);for(let n=0;n<2;n++)box(terrain,p.x+(n-.5)*.54,.52,p.z+.63,.48,.025,.02,0x626e68);sphere(terrain,p.x+.3,1.51,p.z-.2,.14,theme.color);}continue;}
    const base=cylinder(terrain,p.x,type==='b'?-1.45:-.55,p.z,.85,.62,1.8,0x87928a,{segments:6,roughness:1});base.rotation.y=(x+y)%2*.5;
    const tile=box(terrain,p.x,type==='b'?-1.12:.25,p.z,1.25,.38,1.25,(x+y)%3?0xb4b79e:0xbfc3a8,{roughness:.92});tile.userData.cell={x,y};tiles.push(tile);if(type!=='b')box(terrain,p.x,.45,p.z,1.08,.025,1.08,0xc8c8ac,{roughness:1});
    if(type==='w'||type==='b'){const w=box(terrain,p.x,.15,p.z,1.25,.1,1.25,0x73b6bb,{metalness:.5,roughness:.16,opacity:.8});waterMeshes.push(w);if(type==='b'){const bridge=new THREE.Group();bridge.position.set(p.x,.45,p.z);for(let n=0;n<5;n++)box(bridge,(n-2)*.24,0,0,.215,.1,1.15,0xb4a689);for(const z of [-.52,.52])box(bridge,0,-.11,z,1.18,.14,.12,0x7e897c);terrain.add(bridge);bridgeMeshes.push(bridge);}}
    if((x+y*3)%7===0&&type==='.'){for(let i=0;i<3;i++){const grass=box(terrain,p.x+.42+(i-1)*.08,.56+i*.02,p.z-.42,.028,.2,.04,0x7c9a77);grass.rotation.z=(i-1)*.4;}}
  }
  for(const p of l.plates){const v=cell(p);cylinder(mechanisms,v.x,.51,v.z,.43,.46,.08,0x9f8964);torus(mechanisms,v.x,.565,v.z,.3,.035,0xe4c389,Math.PI/2);cylinder(mechanisms,v.x,.565,v.z,.21,.21,.02,0xc4ac74);}
  for(const c of state.crates){const m=crateModel();m.position.copy(cell(c));mechanisms.add(m);crateMeshes.push(m);}
  for(const m of state.mirrors){const g=mirrorModel();g.position.copy(cell(m));mechanisms.add(g);mirrorMeshes.push(g);}
  if(l.emitter){const p=cell(l.emitter),g=new THREE.Group();g.position.copy(p);cylinder(g,0,0,0,.45,.6,.5,0x889e95);cylinder(g,0,.45,0,.27,.3,.6,0xadbcaa);const orb=crystal(g,0,.9,0,.24,0xe6d397);torus(g,0,.9,0,.38,.055,0xdac495);g.rotation.y=-l.emitter.direction*Math.PI/2;mechanisms.add(g);}
  if(l.receiver){const p=cell(l.receiver);cylinder(mechanisms,p.x,.63,p.z,.3,.4,.28,0xc1b89a);crystal(mechanisms,p.x,1.22,p.z,.25,0xe2cf8c);torus(mechanisms,p.x,1.25,p.z,.45,.045,0xbab99a);}
  for(const v of l.valves){const g=valveModel();g.position.copy(cell(v));mechanisms.add(g);valveMeshes.push(g);}
  for(let y=0;y<9;y++)for(let x=0;x<9;x++)if(l.tiles[y][x]==='g'){const p=cell({x,y}),g=new THREE.Group();g.position.copy(p);const alongX=l.tiles[y]?.[x-1]==='.'||l.tiles[y]?.[x-1]==='w'||l.tiles[y]?.[x-1]==='b';g.rotation.y=alongX?Math.PI/2:0;for(const side of [-1,1]){cylinder(g,side*.58,.85,0,.13,.2,1.8,0x9ea798);sphere(g,side*.58,1.86,0,.16,0xd9c29a);}box(g,0,1.72,0,1.45,.22,.4,0xb3b99f);gateMesh=new THREE.Group();for(let i=0;i<5;i++)box(gateMesh,(i-2)*.22,.77,0,.08,1.45,.09,0xbba273);box(gateMesh,0,.3,0,1.08,.06,.12,0xdec29a);g.add(gateMesh);mechanisms.add(g);gateY=0;}
  const exit=cell(l.goal);const arch=new THREE.Group();arch.position.copy(exit);for(const x of [-.48,.48])cylinder(arch,x,.7,0,.09,.12,1.4,0xb7bca3);const arc=torus(arch,0,1.32,0,.5,.07,theme.color);arc.scale.y=.75;crystal(arch,0,1.75,0,.16,0xe8dca8);label(arch,'归航',0,2.13,0,{size:.22,color:'#ecedc9'});mechanisms.add(arch);
  for(const p of l.collectibles){const v=cell(p),g=new THREE.Group();g.position.set(v.x,1.1,v.z);const star=crystal(g,0,0,0,.18,0xf6df97);star.scale.y=1.4;torus(g,0,-.07,0,.28,.017,0xe2d6a2,Math.PI/2);mechanisms.add(g);stars.push(g);}
  for(let i=0;i<7;i++){const a=(i/7)*Math.PI*2+.3,r=7.8+i%2*.8;const x=Math.sin(a)*r,z=Math.cos(a)*r;cylinder(backdrop,x,-1,z,1.15,.7,1.6,0x869d91,{segments:7});cylinder(backdrop,x,-.12,z,1.13,1.16,.16,theme.color,{segments:7});tree(backdrop,x,z,l.island);}
  if(l.island===5){const orbit=torus(backdrop,0,5,0,8,.025,0xc4c5d7,Math.PI/2.8);decorMotions.push(orbit);for(let i=0;i<8;i++)crystal(backdrop,Math.sin(i*3)*13,4+i%3,Math.cos(i*3)*13,.12,0xd9d6da);}
  avatar=explorer();avatar.position.copy(cell(state.player));actors.add(avatar);fitCamera();syncMechanisms();
}
function fitCamera(){const mobile=innerWidth/innerHeight<.85,r=mobile?24:15.6,h=mobile?26:18;game.camera.fov=46;game.camera.position.set(Math.sin(angle)*r,h,Math.cos(angle)*r);game.camera.lookAt(0,.3,0);game.camera.updateProjectionMatrix();}
window.addEventListener('resize',fitCamera);
function syncMechanisms(){const lit=traceLight(state);const k=JSON.stringify([lit.segments,lit.lit]);if(k!==beamKey){clearGroup(beam);for(const seg of lit.segments){const a=cell(seg.from),b=cell(seg.to);a.y=b.y=1.38;tube(beam,a,b,.027,lit.lit?0xffe7a4:0xdcd390,true);}beamKey=k;}
  mirrorMeshes.forEach((m,i)=>{m.userData.head.rotation.y=state.mirrors[i].rotation===1?Math.PI/4:-Math.PI/4;});valveMeshes.forEach(v=>v.userData.wheel.rotation.z=state.water?Math.PI/2:0);note.innerHTML=`<b>${ISLANDS[state.level.island].mechanic} · ${gateOpen(state)?'中央门已开启':'中央门待接通'}</b><p>${state.level.hint}${state.level.valves.length?` 当前：${state.water?'高水位':'低水位'}。`:''}<br>镜头 ${turn*90}° · ↑ ${['北','西','南','东'][turn]} / → ${['东','北','西','南'][turn]} · 两颗星屑为额外收集。</p>`;
}
function start(id=selected){selected=id;island=Math.floor(id/8);state=createPuzzle(id);ended=false;hints=0;turn=0;angle=angleTarget=Math.PI/4;wait=0;buildIsland(state.level);game.ui.hideOverlay();note.hidden=false;game.ui.hint('方向键 移动 · 空格 操作 · Q/E 转视角 · Z 撤销 · H 提示');}
function showMenu(){note.hidden=true;game.ui.overlay({title:'一座岛，一点发现。',text:'穿过苔色石阶、琥珀光庭与潮汐水湾。把机关接回正确的位置，让归航门再次亮起。',body:`<div class="choice-grid">${ISLANDS.map((a,i)=>`<button class="choice ${i===island?'selected':''}" data-island="${i}"><strong>${a.name}</strong><small>${a.mechanic} · 8 关</small></button>`).join('')}</div><div class="island-levels">${LEVELS.filter(l=>l.island===island).map(l=>`<button data-level="${l.id}" class="${l.id===selected?'selected':''}" ${l.id>=save.unlocked?'disabled':''}><b>${String(l.id+1).padStart(2,'0')}</b><small>${l.name}</small><small>${l.id<save.unlocked?(save.stars[l.id]?'★'.repeat(save.stars[l.id]):'尚未探索'):'完成前关解锁'}</small></button>`).join('')}</div><div class="island-legend"><span>木箱 → 圆形压板</span><span>反射镜 → 发光水晶</span><span>水阀 → 石路 / 浮桥</span><span>星屑 → 额外星章</span></div><p class="muted">关卡 ${selected+1}：${LEVELS[selected].hint}<br>无限撤销与重新开始。提示根据当前机关状态计算，使用提示仍可正常通关。</p>`,buttons:[{label:'登岛探索',primary:true,disabled:selected>=save.unlocked,onClick:()=>start(selected)},...(state?.status==='running'?[{label:'继续当前',onClick:()=>{selected=state.level.id;island=state.level.island;note.hidden=false;game.ui.hideOverlay();}}]:[])]});document.querySelectorAll('[data-island]').forEach(b=>b.onclick=()=>{island=Number(b.dataset.island);selected=island*8;showMenu();});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.level);showMenu();});}
function undo(){if(!state||!undoPuzzle(state)){game.ui.toast('还没有可以撤销的行动。');return;}ended=false;syncMechanisms();game.sound(230,.05,'sine');}
function hint(){const path=solveLevel(state.level,100000,state);hints++;if(!path){game.ui.toast('这条路暂时无法归航，试试撤销刚才推箱的步骤。');return;}const names=['↑','→','↓','←'];const actions=path.slice(0,5).map(a=>a==='interact'?'空格操作':names[(a+turn)%4]);game.ui.toast(`下一步：${actions.join('　')}　（还需 ${path.length} 步）`);}
function finish(){ended=true;if(state.status==='lost'){game.ui.overlay({title:'木箱卡在死角了',text:'这只木箱已无法离开墙角。撤销一步，重新安排推动的方向。',buttons:[{label:'撤销并继续',primary:true,onClick:()=>{undo();game.ui.hideOverlay();}},{label:'重新布置',onClick:()=>start(state.level.id)},{label:'返回群岛',onClick:showMenu}]});return;}const collected=state.level.collectibles.filter((_,i)=>state.collected&(1<<i)).length;const score=1+(collected===2?1:0)+(hints===0?1:0);save.stars[state.level.id]=Math.max(save.stars[state.level.id],score);save.unlocked=Math.max(save.unlocked,Math.min(48,state.level.id+2));save.bestMoves[state.level.id]=save.bestMoves[state.level.id]===0?state.moves:Math.min(save.bestMoves[state.level.id],state.moves);game.save(save);note.hidden=true;game.ui.overlay({title:'归航门，亮了。',text:`${'★'.repeat(score)}  ${ISLANDS[state.level.island].name}的这一段路已经接通。${collected<2?'星屑留在岛上，随时可以再来寻找。':'两颗星屑都已收入行囊。'}`,body:`<div class="choice-grid"><div class="choice"><strong>${state.moves} 步</strong><small>完成机关</small></div><div class="choice"><strong>${collected} / 2</strong><small>星屑收集</small></div><div class="choice"><strong>${hints} 次</strong><small>使用提示</small></div></div>`,buttons:[...(state.level.id<47?[{label:'前往下一座小岛',primary:true,onClick:()=>start(state.level.id+1)}]:[]),{label:'再次探索',onClick:()=>start(state.level.id)},{label:'返回群岛',onClick:showMenu}]});}
function move(action){const before=state.collected;if(actPuzzle(state,action)){game.sound(action==='interact'?400:180,.045,'sine',.025);if(before!==state.collected)game.sound(820,.14,'sine');if(Number.isInteger(action))avatar.userData.facing=action*Math.PI/2;syncMechanisms();}else if(action==='interact')game.ui.toast('先走到镜座或水阀旁，再按操作。');}
game.onMenu(showMenu);
game.run((dt,time)=>{if(!state)return;if(game.input.pressed('KeyR')){start(state.level.id);return;}if(game.input.pressed('KeyZ'))undo();if(game.input.pressed('KeyH'))hint();if(game.input.pressed('KeyQ')||game.input.pressed('KeyE')){const d=game.input.pressed('KeyQ')?-1:1;turn=(turn+d+4)%4;angleTarget+=d*Math.PI/2;syncMechanisms();}if(game.input.pressed('Space'))move('interact');
  wait=Math.max(0,wait-dt);const codes=[['ArrowUp','KeyW'],['ArrowRight','KeyD'],['ArrowDown','KeyS'],['ArrowLeft','KeyA']];for(let direction=0;direction<4;direction++)if(codes[direction].some(c=>game.input.pressed(c)||(game.input.held(c)&&wait===0))){move((direction-turn+4)%4);wait=.17;break;}
  if(game.input.pointer.tap){ray.setFromCamera(new THREE.Vector2(game.input.pointer.x,game.input.pointer.y),game.camera);const intersections=ray.intersectObjects(tiles);if(intersections[0]){const p=intersections[0].object.userData.cell,dx=p.x-state.player.x,dy=p.y-state.player.y;if(Math.abs(dx)+Math.abs(dy)===1){if(state.mirrors.some(m=>m.x===p.x&&m.y===p.y)||state.level.valves.some(v=>v.x===p.x&&v.y===p.y))move('interact');else move(dx===1?1:dx===-1?3:dy===1?2:0);}else if(dx===0&&dy===0)move('interact');}}
  angle+=(angleTarget-angle)*Math.min(1,dt*8);fitCamera();const destination=cell(state.player),walking=avatar.position.distanceTo(destination)>.03;avatar.position.lerp(destination,Math.min(1,dt*14));avatar.rotation.y=avatar.userData.facing||0;avatarLegs.forEach((l,i)=>l.rotation.x=walking?Math.sin(time*18)*(i?-.5:.5):0);
  crateMeshes.forEach((m,i)=>m.position.lerp(cell(state.crates[i]),Math.min(1,dt*12)));waterMeshes.forEach((m,i)=>{const target=state.water?.51:-.37;m.position.y+=(target-m.position.y)*Math.min(1,dt*2);m.position.y+=Math.sin(time*2+i)*.0009;});bridgeMeshes.forEach(m=>{const target=state.water?.46:-.3;m.position.y+=(target-m.position.y)*Math.min(1,dt*3);});gateY+=( (gateOpen(state)?1.55:0)-gateY)*Math.min(1,dt*5);if(gateMesh)gateMesh.position.y=gateY;
  stars.forEach((s,i)=>{s.visible=!(state.collected&(1<<i));s.position.y=1.12+Math.sin(time*2+i)*.09;s.rotation.y=time*.7;});trees.forEach((t,i)=>t.rotation.z=Math.sin(time*.7+i)*.015);decorMotions.forEach((m,i)=>m.rotation.z+=dt*.04*(i%2?1:-1));
  game.ui.stats([{label:'探索进度',value:`${state.level.id+1} / 48`},{label:'行动',value:state.moves},{label:'星屑',value:`${(state.collected&1?1:0)+(state.collected&2?1:0)} / 2`},{label:'机关门',value:gateOpen(state)?'开启':'待接通'}]);if(state.status!=='running'&&!ended)finish();
});
state=createPuzzle(selected);buildIsland(state.level);state=null;showMenu();
