import {clamp,createInputState} from './core.mjs';
export const THREE=globalThis.THREE;
function material(color,options={}){return new THREE.MeshStandardMaterial({color,roughness:options.roughness??.65,metalness:options.metalness??.1,...(options.emissive!==undefined?{emissive:options.emissive,emissiveIntensity:options.emissiveIntensity??.5}:{}) ,...(options.opacity!==undefined?{opacity:options.opacity,transparent:true}:{})});}
function mesh(parent,geometry,x,y,z,color,options){const m=new THREE.Mesh(geometry,material(color,options));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;if(options?.rotation)m.rotation.set(...options.rotation);parent.add(m);return m;}
export function box(parent,x,y,z,w,h,d,color,options={}){return mesh(parent,new THREE.BoxGeometry(w,h,d),x,y,z,color,options);}
export function sphere(parent,x,y,z,r,color,options={}){return mesh(parent,new THREE.SphereGeometry(r,options.segments??16,12),x,y,z,color,options);}
export function cylinder(parent,x,y,z,top,bottom,height,color,options={}){return mesh(parent,new THREE.CylinderGeometry(top,bottom,height,options.segments??16),x,y,z,color,options);}
export function label(parent,text,x,y,z,{color='#ffffff',size=1.4}={}){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.font='bold 52px "Microsoft YaHei",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillText(text,256,64,490);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));sprite.position.set(x,y,z);sprite.scale.set(size*4,size,1);parent.add(sprite);return sprite;}
export function clearGroup(group){const geometries=new Set(),materials=new Set(),textures=new Set();group.traverse(obj=>{if(obj.geometry)geometries.add(obj.geometry);for(const m of (Array.isArray(obj.material)?obj.material:obj.material?[obj.material]:[])){materials.add(m);for(const value of Object.values(m))if(value?.isTexture)textures.add(value);}});while(group.children.length)group.remove(group.children[0]);geometries.forEach(x=>x.dispose());materials.forEach(x=>x.dispose());textures.forEach(x=>x.dispose());}
export function createGame({id,title,subtitle='',accent='#79dfbb',help='',background=0x101c2a}){
  document.title=title+' · AMM Lab';document.documentElement.style.setProperty('--accent',accent);
  if(!THREE){document.body.textContent='三维运行资源加载失败，请刷新页面重试。';throw new Error('本地 Three.js 未加载');}
  const canvas=document.createElement('canvas');canvas.className='game-canvas';canvas.tabIndex=0;canvas.setAttribute('aria-label',title+'三维游戏画面');document.body.append(canvas);
  let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(error){document.body.textContent='无法启动三维画面。请启用浏览器硬件加速后刷新。';throw error;}
  renderer.setPixelRatio(Math.min(devicePixelRatio||1,matchMedia('(pointer:coarse)').matches?1.5:2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
  const scene=new THREE.Scene();scene.background=new THREE.Color(background);scene.fog=new THREE.Fog(background,65,160);
  scene.add(new THREE.HemisphereLight(0xd7edff,0x343235,1.8));const sun=new THREE.DirectionalLight(0xffeccb,2.5);sun.position.set(-12,28,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.camera.near=.5;sun.shadow.camera.far=110;sun.shadow.bias=-.0006;sun.shadow.normalBias=.05;scene.add(sun);const fill=new THREE.DirectionalLight(0x79bded,.7);fill.position.set(15,8,-12);scene.add(fill);
  const camera=new THREE.PerspectiveCamera(48,1,.1,250);camera.position.set(0,24,28);camera.lookAt(0,0,0);const world=new THREE.Group();scene.add(world);
  const chrome=document.createElement('div');chrome.className='game-chrome';chrome.innerHTML='<header class="game-top"><div class="game-brand"><h1></h1><small></small></div><nav class="game-tools" aria-label="游戏控制"><button data-tool="menu">选关</button><button data-tool="pause">暂停</button><button data-tool="help">帮助</button><button data-tool="sound" aria-pressed="false">声音：关</button><button data-tool="fullscreen">全屏</button></nav></header><div class="game-stats" aria-label="游戏状态"></div><div class="game-hint"></div><div class="game-toast" role="status" aria-live="polite"></div><div class="game-touch"><div class="game-dpad"><button data-code="ArrowUp" aria-label="向上">↑</button><button data-code="ArrowLeft" aria-label="向左">←</button><button data-code="ArrowDown" aria-label="向下">↓</button><button data-code="ArrowRight" aria-label="向右">→</button></div><div class="game-actions"></div></div>';document.body.append(chrome);chrome.querySelector('h1').textContent=title;chrome.querySelector('.game-brand small').textContent=subtitle||'AMM LAB / PLAY';
  const toastElement=chrome.querySelector('.game-toast');document.body.append(toastElement);
  const overlay=document.createElement('div');overlay.className='game-overlay';overlay.hidden=true;overlay.innerHTML='<section class="game-panel" role="dialog" aria-modal="true" aria-labelledby="overlay-title"><p class="panel-eyebrow">AMM LAB · PLAY COLLECTION</p><h2 id="overlay-title"></h2><p class="panel-text"></p><div class="panel-body"></div><div class="panel-buttons"></div></section>';document.body.append(overlay);
  const input=createInputState();input.pointer={x:0,y:0,down:false,tap:false};const abort=new AbortController();const listen=(node,event,fn,options={})=>node.addEventListener(event,fn,{...options,signal:abort.signal});
  let paused=false,disposed=false,suspended=false,last=performance.now(),elapsed=0,raf=0,update=null,menu=null,toastTimer=0,audio=null,audioEnabled=false,statsKey='',focusBefore=null;
  const stopInput=()=>{input.clear();input.pointer.down=false;input.pointer.tap=false;chrome.querySelectorAll('.pressed').forEach(x=>x.classList.remove('pressed'));};
  const ui={
    stats(items){const key=JSON.stringify(items);if(key===statsKey)return;statsKey=key;const root=chrome.querySelector('.game-stats');if(root.children.length!==items.length){root.replaceChildren(...items.map(()=>{const el=document.createElement('div');el.className='game-stat';el.append(document.createElement('small'),document.createElement('strong'));return el;}));}items.forEach((item,i)=>{const el=root.children[i];el.children[0].textContent=item.label;el.children[1].textContent=String(item.value);});},
    hint(text){chrome.querySelector('.game-hint').textContent=text;},
    toast(text){toastElement.textContent=text;toastElement.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastElement.classList.remove('visible'),2800);},
    overlay({title:heading,text='',body='',buttons=[]}){stopInput();paused=true;focusBefore=document.activeElement;overlay.querySelector('h2').textContent=heading;overlay.querySelector('.panel-text').textContent=text;overlay.querySelector('.panel-body').innerHTML=body;const root=overlay.querySelector('.panel-buttons');root.replaceChildren();for(const item of buttons){const b=document.createElement('button');b.textContent=item.label;b.className=item.primary?'primary':'';b.disabled=!!item.disabled;b.addEventListener('click',item.onClick);root.append(b);}overlay.hidden=false;chrome.querySelector('[data-tool="pause"]').textContent='继续';queueMicrotask(()=>overlay.querySelector('select,button,input')?.focus());},
    hideOverlay(){overlay.hidden=true;paused=false;last=performance.now();stopInput();chrome.querySelector('[data-tool="pause"]').textContent='暂停';if(audioEnabled)audio?.resume().catch(()=>ui.toast('声音暂时无法恢复，请重新开启声音。'));canvas.focus({preventScroll:true});}
  };
  function pauseMenu(){if(!overlay.hidden)return;ui.overlay({title:'稍作休息',text:'游戏已暂停，继续后从当前位置出发。',buttons:[{label:'继续游戏',primary:true,onClick:()=>ui.hideOverlay()},{label:'返回选关',onClick:()=>menu?.()}]});}
  function togglePause(){if(!overlay.hidden){if(overlay.querySelector('h2').textContent==='稍作休息')ui.hideOverlay();return;}pauseMenu();}
  function pointerPosition(event){const rect=canvas.getBoundingClientRect();input.pointer.x=((event.clientX-rect.left)/rect.width)*2-1;input.pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;}
  listen(canvas,'pointermove',pointerPosition);listen(canvas,'pointerdown',event=>{pointerPosition(event);input.pointer.down=true;input.pointer.tap=true;canvas.setPointerCapture(event.pointerId);canvas.focus({preventScroll:true});});listen(canvas,'pointerup',()=>{input.pointer.down=false;});listen(canvas,'pointercancel',stopInput);listen(canvas,'contextmenu',event=>event.preventDefault());
  listen(window,'keydown',event=>{if(event.code==='Escape'||event.code==='KeyP'){if(!event.repeat)togglePause();event.preventDefault();return;}if(!overlay.hidden)return;if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement||event.target instanceof HTMLTextAreaElement)return;if(/^(Arrow|Space|Key[WASDEQRFZXCV]|Digit)/.test(event.code))event.preventDefault();input.press(event.code);});listen(window,'keyup',event=>input.release(event.code));
  listen(overlay,'keydown',event=>{if(event.key!=='Tab')return;const items=[...overlay.querySelectorAll('button:not(:disabled),select,input,[tabindex="0"]')];if(!items.length)return;const first=items[0],end=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();end.focus();}else if(!event.shiftKey&&document.activeElement===end){event.preventDefault();first.focus();}});
  function wireControl(button){listen(button,'pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);input.press(button.dataset.code);button.classList.add('pressed');});for(const name of ['pointerup','pointercancel','lostpointercapture'])listen(button,name,()=>{input.release(button.dataset.code);button.classList.remove('pressed');});}
  chrome.querySelectorAll('[data-code]').forEach(wireControl);
  listen(chrome.querySelector('[data-tool="pause"]'),'click',togglePause);listen(chrome.querySelector('[data-tool="menu"]'),'click',()=>menu?.());
  listen(chrome.querySelector('[data-tool="help"]'),'click',()=>{if(!overlay.hidden){ui.toast(help);return;}ui.overlay({title:'操作手册',text:help,buttons:[{label:'回到游戏',primary:true,onClick:()=>ui.hideOverlay()}]});});
  listen(chrome.querySelector('[data-tool="sound"]'),'click',async()=>{audioEnabled=!audioEnabled;try{if(audioEnabled){audio??=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();}else await audio?.suspend();}catch{audioEnabled=false;ui.toast('浏览器暂时无法启用声音，请检查音频权限。');}const button=chrome.querySelector('[data-tool="sound"]');button.textContent='声音：'+(audioEnabled?'开':'关');button.setAttribute('aria-pressed',String(audioEnabled));});
  listen(chrome.querySelector('[data-tool="fullscreen"]'),'click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else ui.toast('当前浏览器不支持全屏，请使用横屏游玩。');}catch{ui.toast('全屏未能开启，请使用独立页面或检查浏览器权限。');}});
  const layoutTouch=()=>{const rect=chrome.querySelector('.game-touch').getBoundingClientRect();if(rect.height)chrome.style.setProperty('--touch-hint-bottom',(innerHeight-rect.top+12)+'px');};
  const resize=()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/Math.max(1,innerHeight);camera.updateProjectionMatrix();layoutTouch();};listen(window,'resize',resize);resize();
  listen(document,'visibilitychange',()=>{if(document.hidden){stopInput();pauseMenu();audio?.suspend();}else if(audioEnabled)audio?.resume().catch(()=>{});});listen(window,'blur',()=>{stopInput();pauseMenu();});
  const game={THREE,scene,camera,renderer,world,input,ui,sun,get paused(){return paused;},
    controls(items){const root=chrome.querySelector('.game-actions');root.replaceChildren();for(const item of items){const b=document.createElement('button');b.dataset.code=item.code;b.textContent=item.label;b.setAttribute('aria-label',item.label);root.append(b);wireControl(b);}layoutTouch();},
    onMenu(fn){menu=fn;},setPaused(value){paused=!!value;stopInput();last=performance.now();},
    run(fn){update=fn;},
    sound(freq=440,duration=.1,type='sine',volume=.04){if(!audioEnabled||!audio||audio.state!=='running'||paused)return;try{const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(clamp(freq,30,18000),audio.currentTime);gain.gain.setValueAtTime(clamp(volume,0,.15),audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);osc.onended=()=>{osc.disconnect();gain.disconnect();};}catch{}},
    load(fallback){try{const text=localStorage.getItem('amm-arcade-'+id+'-v1');return text===null?fallback:JSON.parse(text);}catch{ui.toast('本地记录无法读取，已使用初始进度。');return fallback;}},
    save(value){try{localStorage.setItem('amm-arcade-'+id+'-v1',JSON.stringify(value));return true;}catch{ui.toast('本地记录保存失败，请检查浏览器存储空间。');return false;}},
    dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);abort.abort();clearTimeout(toastTimer);stopInput();clearGroup(scene);renderer.dispose();audio?.close().catch(()=>{});}
  };
  listen(window,'pagehide',event=>{if(!event.persisted){game.dispose();return;}stopInput();pauseMenu();paused=true;suspended=true;cancelAnimationFrame(raf);audio?.suspend().catch(()=>{});});
  listen(window,'pageshow',event=>{if(!event.persisted||disposed||!suspended)return;suspended=false;last=performance.now();stopInput();pauseMenu();raf=requestAnimationFrame(frame);});
  listen(canvas,'webglcontextlost',event=>{event.preventDefault();paused=true;ui.overlay({title:'三维画面暂时中断',text:'浏览器释放了图形资源。刷新页面可恢复，本地保存的进度会保留。',buttons:[{label:'刷新页面',primary:true,onClick:()=>location.reload()}]});});
  function frame(now){if(disposed||suspended)return;const dt=clamp((now-last)/1000,0,.04);last=now;if(!paused&&update){elapsed+=dt;try{update(dt,elapsed);}catch(error){console.error(error);ui.overlay({title:'游戏运行遇到问题',text:'请重新载入本关。已保存的进度会保留。',buttons:[{label:'返回选关',onClick:()=>menu?.()},{label:'刷新',onClick:()=>location.reload()}]});}}input.endFrame();input.pointer.tap=false;renderer.render(scene,camera);raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);return game;
}
