const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const int=(n,a,b,d=a)=>Number.isFinite(n)?clamp(Math.floor(n),a,b):d;
export const SHOPS=[{name:'灯笼面屋',tag:'LANTERN NOODLES',color:0xe4a568,description:'汤锅、煎台与冷案，共同照料雨夜食客。'},{name:'海风铁板',tag:'SEASIDE GRIDDLE',color:0x78c4c5,description:'海边夜市的烤物、汤品与鲜食。'},{name:'月光甜房',tag:'MOONLIGHT PATISSERIE',color:0xc9a5df,description:'小烤炉、糖浆锅与冰台的甜品协作。'}];
const data=[
 ['清汤拉面',0,5,18,['面条','清汤','葱花'],'noodle'],['味噌玉子面',0,6,23,['味噌','玉子','面条'],'noodle'],['红油担担面',0,7,27,['肉末','花生','辣油'],'noodle'],['香菇乌冬',0,6,24,['乌冬','香菇','昆布'],'noodle'],
 ['月见煎饺',1,6,22,['饺子','鸡蛋','芝麻'],'dumpling'],['葱香饭团',1,5,19,['米饭','海苔','青葱'],'rice'],['凉拌豆腐',2,3,16,['豆腐','木鱼花','酱油'],'tofu'],['柚子冷面',2,4,25,['荞麦','柚子','黄瓜'],'noodle'],
 ['海盐虾串',1,5,28,['鲜虾','海盐','青柠'],'skewer'],['照烧鸡串',1,6,26,['鸡肉','照烧汁','大葱'],'skewer'],['海风鱿鱼',1,7,32,['鱿鱼','蒜蓉','辣椒'],'squid'],['蔬菜铁板',1,4,23,['甜椒','玉米','西葫芦'],'vegetable'],
 ['蛤蜊汤',0,5,27,['蛤蜊','白萝卜','姜丝'],'soup'],['海鲜泡饭',0,7,34,['米饭','扇贝','鱼汤'],'rice'],['番茄沙拉',2,3,20,['番茄','罗勒','芝士'],'salad'],['青柠汽水',2,3,18,['青柠','苏打','薄荷'],'drink'],
 ['蜂蜜松饼',1,5,25,['松饼','蜂蜜','黄油'],'pancake'],['莓果可丽饼',1,6,30,['饼皮','草莓','奶油'],'crepe'],['焦糖布丁',0,6,28,['鸡蛋','牛奶','焦糖'],'pudding'],['热可可',0,4,22,['可可','牛奶','棉花糖'],'drink'],
 ['抹茶团子',0,5,24,['糯米','抹茶','红豆'],'dango'],['草莓圣代',2,4,31,['草莓','冰淇淋','脆饼'],'sundae'],['蓝莓挞',1,7,35,['挞皮','蓝莓','卡仕达'],'tart'],['蜜桃冰沙',2,3,24,['蜜桃','碎冰','迷迭香'],'drink']
];
export const RECIPES=data.map(([name,station,cook,price,ingredients,shape],id)=>({id,name,station,cook,price,ingredients,shape,shop:Math.floor(id/8)}));
export const DAYS=Array.from({length:30},(_,id)=>{const shop=Math.floor(id/10),day=id%10;return {id,shop,name:['试营业','夜归人','雨中来客','双台协作','新品上桌','晚班列车','小街节庆','食客高峰','主厨试炼','满月营业'][day],recipes:Array.from({length:Math.min(8,2+day)},(_,i)=>shop*8+i),target:3+Math.floor(day/2)+shop,duration:58+day*6+shop*5,interval:Math.max(4.5,8.5-day*.32-shop*.4),patience:34-day*.5,maxMissed:4};});
export const UPGRADES=[{id:'heat',name:'恒温炉芯',text:'每级缩短烹饪时间 12%',cost:80},{id:'patience',name:'舒适座椅',text:'每级增加食客耐心 6 秒',cost:65},{id:'tips',name:'精致餐具',text:'每级增加售价 15%',cost:75}];
export function validateSave(v){v=v&&typeof v==='object'?v:{};return {version:1,coins:int(v.coins,0,999999),unlocked:int(v.unlocked,1,30,1),days:Array.from({length:30},(_,i)=>int(v.days?.[i],0,3)),upgrades:Object.fromEntries(UPGRADES.map(u=>[u.id,int(v.upgrades?.[u.id],0,3)]))};}
export function buyUpgrade(s,key){const u=UPGRADES.find(x=>x.id===key);if(!u)return false;const rank=s.upgrades[key];if(rank>=3)return false;const price=u.cost*(rank+1);if(s.coins<price)return false;s.coins-=price;s.upgrades[key]++;return true;}
function addOrder(s){const occupied=new Set(s.orders.filter(o=>o.status!=='served'&&o.status!=='left').map(o=>o.seat));if(occupied.size>=5)return false;const seat=[0,1,2,3,4].find(n=>!occupied.has(n)),n=s.generated++,recipe=s.day.recipes[(n*3+Math.floor(n/3)+s.day.id)%s.day.recipes.length];s.orders.push({id:s.nextId++,recipe,patience:s.day.patience+s.upgrades.patience*6,maxPatience:s.day.patience+s.upgrades.patience*6,status:'waiting',guest:n%8,seat});s.events.push({type:'arrive'});return true;}
export function createDay(day=0,upgrades={}){const d=DAYS[int(day,0,29)];const s={day:d,status:'running',time:d.duration,elapsed:0,orders:[],stations:Array.from({length:3},()=>({order:null,recipe:null,remaining:0,duration:0,readyAge:0,status:'empty'})),upgrades:validateSave({upgrades}).upgrades,revenue:0,served:0,missed:0,waste:0,nextId:1,generated:0,arrival:d.interval,events:[],combo:0,bestCombo:0};addOrder(s);return s;}
export function takeOrder(s,id){if(s.status!=='running')return false;const o=s.orders.find(x=>x.id===id);if(!o||o.status!=='waiting')return false;const r=RECIPES[o.recipe],station=s.stations[r.station];if(station.status!=='empty')return false;o.status='cooking';Object.assign(station,{order:id,recipe:o.recipe,remaining:r.cook*(1-s.upgrades.heat*.12),duration:r.cook*(1-s.upgrades.heat*.12),readyAge:0,status:'cooking'});s.events.push({type:'cook',station:r.station});return true;}
export function serveOrder(s,id){if(s.status!=='running')return false;const o=s.orders.find(x=>x.id===id),station=s.stations.find(x=>x.order===id&&x.status==='ready');if(!o||o.status!=='ready'||!station)return false;const r=RECIPES[o.recipe];s.combo++;s.bestCombo=Math.max(s.bestCombo,s.combo);const income=Math.round(r.price*(1+s.upgrades.tips*.15)*(1+(o.patience/o.maxPatience>.5?.2:0)));s.revenue+=income;s.served++;o.status='served';Object.assign(station,{order:null,recipe:null,status:'empty',remaining:0,readyAge:0});s.events.push({type:'serve',income});if(s.served>=s.day.target)s.status='won';return true;}
export function discardDish(s,index){const station=s.stations[index];if(s.status!=='running'||!station||station.status==='empty')return false;const alreadyWasted=station.status==='burnt',o=s.orders.find(x=>x.id===station.order);if(o&&o.status!=='left')o.status='waiting';Object.assign(station,{order:null,recipe:null,status:'empty',remaining:0,readyAge:0});if(!alreadyWasted)s.waste++;s.combo=0;return true;}
export function stepDay(s,dt){if(s.status!=='running')return;dt=clamp(dt,0,120);s.events=[];s.time=Math.max(0,s.time-dt);s.elapsed+=dt;s.arrival-=dt;
  for(const station of s.stations){if(station.status==='cooking'){station.remaining-=dt;if(station.remaining<=0){station.status='ready';station.readyAge=-station.remaining;const o=s.orders.find(x=>x.id===station.order);if(o&&o.status!=='left')o.status='ready';s.events.push({type:'ready'});}}else if(station.status==='ready')station.readyAge+=dt;
    if(station.status==='ready'&&station.readyAge>9){station.status='burnt';s.waste++;s.combo=0;const o=s.orders.find(x=>x.id===station.order);if(o&&o.status!=='left')o.status='waiting';s.events.push({type:'burn'});}
  }
  for(const o of s.orders){if(o.status==='served'||o.status==='left')continue;o.patience-=dt;if(o.patience<=0){o.status='left';s.missed++;s.combo=0;s.events.push({type:'leave'});const st=s.stations.find(x=>x.order===o.id);if(st&&st.status!=='empty')Object.assign(st,{order:null,recipe:null,status:'empty'});}}
  if(s.arrival<=0){if(addOrder(s))s.arrival+=s.day.interval;else s.arrival=1;}
  if(s.missed>=s.day.maxMissed||s.time<=0)s.status=s.served>=s.day.target?'won':'lost';
  if(s.orders.length>24)s.orders=s.orders.filter(o=>o.status!=='served'&&o.status!=='left');
}
