import { THREE, createGame, box, sphere, cylinder, label, clearGroup } from '../arcade-runtime/runtime.mjs';
import { MAPS, CHARACTERS, WEAPONS, PASSIVES, createRun, stepRun, chooseUpgrade, sanitizeSave, settleRun, buyGrowth } from './core.mjs';

const game = createGame({ id: 'glimmer-survivor', title: '微光幸存者', subtitle: 'GLIMMER / THE LAST LANTERN', accent: '#a9e3c6', help: 'WASD / 方向键移动，Space 冲刺。武器自动攻击；靠近青色结晶拾取经验，升级时三选一。武器四级并持有对应媒介后自动进化。抵达最终时刻并击败 Boss 胜利。P / Esc 暂停。手机使用方向盘与冲刺按钮。', background: 0x142c2a });
game.controls([{ code: 'Space', label: '冲刺' }]);
let save = sanitizeSave(game.load(null)), state, hero, terrain, entities, ornaments = [], lastPhase = '', selectedMap = 0, selectedCharacter = 0, shownLoadout = '', lastSound = 0;
const cache = new Map(), ray = new THREE.Raycaster();
const loadout = document.createElement('div'); loadout.className = 'survivor-loadout'; document.body.append(loadout);
const xp = document.createElement('div'); xp.className = 'survivor-xp'; xp.innerHTML = '<i></i>'; document.body.append(xp);
const palettes = [{ ground: 0x365d4d, rim: 0x203c36, plant: 0x578677, accent: 0x92e5c8 }, { ground: 0x526b79, rim: 0x263f50, plant: 0x8fa8af, accent: 0x8fd3e9 }, { ground: 0x5b4138, rim: 0x322d31, plant: 0x80675c, accent: 0xffaa78 }, { ground: 0xad9770, rim: 0x766553, plant: 0xc7b687, accent: 0xede8c4 }, { ground: 0x655a79, rim: 0x39364c, plant: 0x9a8bad, accent: 0xceb8f1 }];
const material = (color, extra = {}) => new THREE.MeshStandardMaterial({ color, roughness: .72, metalness: .08, ...extra });
function mesh(parent, geometry, color, x = 0, y = 0, z = 0, extra = {}) { const m = new THREE.Mesh(geometry, material(color, extra)); m.position.set(x, y, z); m.castShadow = true; m.receiveShadow = true; parent.add(m); return m; }
function ring(parent, radius, tube, color, y = 0) { const m = mesh(parent, new THREE.TorusGeometry(radius, tube, 6, 40), color, 0, y, 0, { emissive: color, emissiveIntensity: .18 }); m.rotation.x = Math.PI / 2; return m; }
function branch(parent, a, b, radius, color) { const dir = new THREE.Vector3().subVectors(b, a), obj = cylinder(parent, 0, 0, 0, radius * .62, radius, dir.length(), color, { segments: 7 }); obj.position.copy(a).add(b).multiplyScalar(.5); obj.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), dir.normalize()); return obj; }
function rock(parent, x, y, z, radius, color, seed = 0) { const m = mesh(parent, new THREE.DodecahedronGeometry(radius, 0), color, x, y, z); m.scale.set(1.1, .65 + (seed % 3) * .16, .8); m.rotation.set(seed * .3, seed * .8, seed * .13); return m; }
function crystal(parent, x, y, z, scale, color) { const m = mesh(parent, new THREE.OctahedronGeometry(scale, 0), color, x, y, z, { roughness: .18, metalness: .35, emissive: color, emissiveIntensity: .24 }); m.scale.y = 1.8; return m; }
function mushroom(parent, x, z, scale, color) { const g = new THREE.Group(); parent.add(g); g.position.set(x, 0, z); g.scale.setScalar(scale); cylinder(g, 0, .35, 0, .11, .18, .7, 0xa6b6a2); const cap = sphere(g, 0, .8, 0, .5, color, { emissive: color, emissiveIntensity: .18 }); cap.scale.y = .35; for (let i = 0; i < 4; i++) sphere(g, Math.cos(i * 2.4) * .3, .91, Math.sin(i * 2.4) * .3, .055, 0xdfedcc); }
function tree(parent, x, z, scale, color, bare = false) {
  const g = new THREE.Group(); parent.add(g); g.position.set(x, 0, z); g.scale.setScalar(scale);
  cylinder(g, 0, 1.3, 0, .28, .55, 2.6, 0x675b47, { segments: 7 });
  for (let i = 0; i < 5; i++) { const a = i * Math.PI * .4; branch(g, new THREE.Vector3(0, 1.2 + i % 2 * .5, 0), new THREE.Vector3(Math.cos(a) * 1.15, 2.6 + i % 2 * .5, Math.sin(a) * 1.15), .16, 0x675b47); branch(g, new THREE.Vector3(0, .25, 0), new THREE.Vector3(Math.cos(a) * 1.1, .05, Math.sin(a) * 1.1), .18, 0x635940); if (!bare) { const crown = rock(g, Math.cos(a) * .9, 2.8 + i % 2 * .5, Math.sin(a) * .9, 1.05, color, i); crown.scale.y = .8; } }
}
function buildWorld() {
  clearGroup(game.world); cache.clear(); ornaments = []; terrain = new THREE.Group(); entities = new THREE.Group(); game.world.add(terrain, entities); const p = palettes[state.map];
  game.scene.background.setHex([0x142d2a, 0x182c3b, 0x30292c, 0x464238, 0x24243a][state.map]); game.scene.fog.color.copy(game.scene.background); game.scene.fog.near = 58;
  cylinder(terrain, 0, -.9, 0, 17.9, 17, 1.8, p.rim, { segments: 80 }); cylinder(terrain, 0, -.1, 0, 17.6, 17.9, .45, p.ground, { segments: 80 }); ring(terrain, 17.65, .12, p.plant, .15);
  for (let i = 0; i < 72; i++) { const a = i * 2.399, r = 3.2 + Math.sqrt((i * 47) % 997 / 997) * 13.5, x = Math.cos(a) * r, z = Math.sin(a) * r; if (state.terrain.some(t => Math.hypot(x - t.x, z - t.z) < t.radius + .5)) continue; rock(terrain, x, .02, z, .16 + i % 3 * .06, p.plant, i); if (state.map === 0 && i % 3 === 0) mushroom(terrain, x + .3, z, .5, 0x8ed8bd); if (state.map === 3 && i % 5 === 0) { const dune = sphere(terrain, x, .1, z, 1.4, 0xb9a17c); dune.scale.set(1.5, .12, .6); dune.rotation.y = -.4; } }
  for (let i = 0; i < 36; i++) { const a = i / 36 * Math.PI * 2; rock(terrain, Math.cos(a) * 17.7, -.1, Math.sin(a) * 17.7, .6 + i % 3 * .13, p.rim, i); }
  for (const [index, t] of state.terrain.entries()) {
    const g = new THREE.Group(); terrain.add(g); g.position.set(t.x, 0, t.z);
    if (state.map === 0) { tree(g, 0, 0, .85 + index % 3 * .14, [0x658775, 0x456e5b, 0x718c6b][index % 3]); mushroom(g, .7, .6, .75, p.accent); }
    if (state.map === 1) { cylinder(g, 0, .35, 0, 1.7, 1.8, .65, 0x75828a, { segments: 8 }); for (let j = -1; j <= 1; j += 2) { cylinder(g, j * 1.1, 1.8, 0, .22, .34, 2.6, 0xa0b1b7); cylinder(g, j * 1.1, 3.1, 0, .42, .42, .22, 0xa8b3b2); } const arch = mesh(g, new THREE.TorusGeometry(1.1, .23, 8, 18, Math.PI), 0xa4b5b8, 0, 3.1, 0); arch.rotation.z = 0; const pool = cylinder(g, 0, .08, 0, 2.45, 2.45, .06, 0x3f8199, { opacity: .6, emissive: 0x315d76 }); ornaments.push({ type: 'water', mesh: pool }); }
    if (state.map === 2) { const lava = cylinder(g, 0, .12, 0, 2, 2, .08, 0xec8753, { emissive: 0xef622e, emissiveIntensity: .6 }); ornaments.push({ type: 'lava', mesh: lava }); for (let j = 0; j < 7; j++) { const a = j / 7 * Math.PI * 2; rock(g, Math.cos(a) * 2, .35, Math.sin(a) * 2, .62, 0x494046, j); } if (index % 3 === 0) { const spire = mesh(g, new THREE.ConeGeometry(.85, 2.8, 5), 0x413b42, 1, 1.1, 1); spire.rotation.z = -.3; } }
    if (state.map === 3) { const sand = cylinder(g, 0, .11, 0, 2.1, 2.1, .02, 0x8c7c5c, { opacity: .65 }); for (let j = 0; j < 3; j++) { const c = crystal(g, (j - 1) * .6, .65 + j * .25, .2, .36 + j * .13, 0xdad6b1); c.rotation.z = (j - 1) * .25; } ring(g, 1.8, .035, 0xc5b589, .14); ornaments.push({ type: 'sand', mesh: sand }); }
    if (state.map === 4) { cylinder(g, 0, .4, 0, .9, 1.2, .8, 0x807291, { segments: 6 }); const c = crystal(g, 0, 1.6, 0, .65, p.accent); const r = ring(g, 1.25, .06, 0xc7afd8, 1.6); r.rotation.x = .45; ornaments.push({ type: 'crystal', mesh: c }); }
  }
  if (state.map === 0) { const pool = cylinder(terrain, 0, .14, 0, 2.25, 2.25, .04, 0x5db59f, { opacity: .6, emissive: 0x438b7b }); ring(terrain, 2.25, .05, 0x93cfab, .17); ornaments.push({ type: 'water', mesh: pool }); }
  if (state.map === 4) { const r = ring(terrain, 8, .08, 0xb09bda, .15); ornaments.push({ type: 'pulse', mesh: r }); }
  const pos = []; for (let i = 0; i < 90; i++) pos.push(Math.cos(i * 2.399) * (3 + i % 14), 1.2 + i % 5 * .4, Math.sin(i * 2.399) * (3 + i % 14));
  const geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); const motes = new THREE.Points(geo, new THREE.PointsMaterial({ color: p.accent, size: .075, transparent: true, opacity: .8, depthWrite: false })); terrain.add(motes); ornaments.push({ type: 'motes', mesh: motes });
  hero = makeHero(state.character); entities.add(hero); hero.position.set(state.player.x, .1, state.player.z);
}
function makeHero(index) {
  const g = new THREE.Group(), c = CHARACTERS[index].color;
  const cloak = cylinder(g, 0, .72, 0, .3, .53, 1.08, c, { segments: 9 }); cloak.rotation.x = -.08;
  sphere(g, 0, 1.47, 0, .31, 0xe7d9b6); const hood = sphere(g, 0, 1.52, -.09, .38, c); hood.scale.set(1.08, 1.03, .8); sphere(g, -.105, 1.49, .265, .035, 0x263c37); sphere(g, .105, 1.49, .265, .035, 0x263c37);
  const feet = []; for (const side of [-1, 1]) { const foot = sphere(g, side * .22, .18, .08, .18, 0x454d43); foot.scale.set(.7, .8, 1.35); feet.push(foot); const arm = cylinder(g, side * .4, .87, 0, .11, .13, .62, c, { segments: 7 }); arm.rotation.z = side * .2; }
  cylinder(g, .55, .85, .18, .035, .045, 1.65, 0x9b8262, { segments: 7 }); const lantern = sphere(g, .55, 1.77, .18, .15, 0xf5dc92, { emissive: 0xffd77c, emissiveIntensity: 1.2 }); ring(g, .14, .023, 0xd5bf87, 1.78).position.x = .55;
  if (index === 1) { const shield = mesh(g, new THREE.CylinderGeometry(.37, .37, .12, 9), 0xd1cadd, -.5, 1, .15); shield.rotation.x = Math.PI / 2; }
  if (index === 2) { for (let i = 0; i < 7; i++) { const spike = mesh(g, new THREE.ConeGeometry(.065, .25, 4), 0xf8de9d, Math.cos(i / 7 * Math.PI * 2) * .25, 1.89, Math.sin(i / 7 * Math.PI * 2) * .25); spike.rotation.z = .2; } }
  if (index === 3) { const hat = mesh(g, new THREE.ConeGeometry(.44, .55, 5), 0xe0eef2, 0, 1.96, -.06); hat.rotation.z = .18; }
  if (index === 4) { const halo = mesh(g, new THREE.TorusGeometry(.47, .04, 6, 20), 0xe2c7ff, 0, 1.6, -.12, { emissive: 0x9c70d4, emissiveIntensity: .5 }); halo.rotation.y = .3; }
  if (index === 5) { for (let i = 0; i < 5; i++) { const leaf = sphere(g, Math.cos(i * 1.256) * .28, 1.82, Math.sin(i * 1.256) * .28, .18, 0xd4dda1); leaf.scale.set(.6, .35, 1.2); leaf.rotation.y = -i * 1.256; } }
  g.userData = { feet, lantern }; return g;
}
function makeEnemy(e) {
  const g = new THREE.Group(), c = e.kind === 'boss' ? [0x8ca778, 0xa5a8a4, 0x8f7060, 0xccb18b, 0xa899cf][state.map] : e.elite ? 0xc6ab80 : { crawler: 0x668c7c, runner: 0xacae99, brute: 0x84908c, spitter: 0xa49cbd, moth: 0xbdadb0 }[e.kind];
  if (e.kind === 'crawler' || e.kind === 'runner') { const shell = sphere(g, 0, .52, 0, .55, c); shell.scale.set(e.kind === 'runner' ? .75 : 1, .65, e.kind === 'runner' ? 1.45 : 1); const head = sphere(g, 0, .56, .55, .3, c); head.scale.z = 1.2; for (const side of [-1, 1]) { for (let i = -1; i <= 1; i += 2) { const leg = cylinder(g, side * .43, .28, i * .33, .07, .09, .55, 0x475d55, { segments: 5 }); leg.rotation.z = side * .6; } sphere(g, side * .14, .66, .81, .055, 0xffc68b, { emissive: 0xff944b }); } if (e.kind === 'runner') for (const side of [-1, 1]) mesh(g, new THREE.ConeGeometry(.13, .36, 4), c, side * .17, .97, .48); }
  else if (e.kind === 'brute') { rock(g, 0, .85, 0, .9, c, 2); rock(g, 0, 1.65, .08, .44, 0xb2b5a5, 3); for (const side of [-1, 1]) { rock(g, side * .75, .9, 0, .4, c, side + 3); rock(g, side * .35, .2, .15, .32, c, 4); crystal(g, side * .32, 1.7, 0, .16, 0xa9e5c1); sphere(g, side * .15, 1.7, .43, .055, 0xf5c394, { emissive: 0xe8844d }); } }
  else if (e.kind === 'spitter' || e.kind === 'moth') { sphere(g, 0, .9, 0, .44, c); for (let i = 0; i < 5; i++) { const a = i / 5 * Math.PI * 2; const petal = sphere(g, Math.cos(a) * .38, .85, Math.sin(a) * .38, .3, i % 2 ? c : 0xd4b4d7); petal.scale.set(.5, .4, 1.6); petal.rotation.y = -a; } sphere(g, 0, .95, .42, .15, 0xf4b595, { emissive: 0xed795b }); if (e.kind === 'moth') for (const side of [-1, 1]) { const wing = sphere(g, side * .7, 1.1, -.05, .7, 0xd6b89c); wing.scale.set(1, .08, .65); wing.rotation.z = side * .25; } }
  else {
    if (state.map === 0) { tree(g, 0, 0, 1, c, true); rock(g, 0, 1.3, .15, 1.1, 0x677958); for (const side of [-1, 1]) sphere(g, side * .28, 1.9, 1, .12, 0xefdb9e, { emissive: 0xdfc87b }); ring(g, 1.5, .08, 0xd7c396, 3); }
    if (state.map === 1) { const points = [[0, 0], [1.2, .1], [1, .4], [.8, 1.4], [.4, 2.4], [0, 2.5]].map(([x, y]) => new THREE.Vector2(x, y)); mesh(g, new THREE.LatheGeometry(points, 18), c, 0, .3, 0, { metalness: .55, roughness: .35 }); ring(g, 1.2, .1, 0xe1cf9b, .4); sphere(g, 0, 1.2, .87, .18, 0x8ad4ef, { emissive: 0x79c3df }); }
    if (state.map === 2) { for (let i = 0; i < 6; i++) rock(g, Math.sin(i) * .5, .5 + i * .32, Math.cos(i) * .3, .9 - i * .07, c, i); sphere(g, 0, 1.25, .65, .4, 0xffad61, { emissive: 0xff7a37, emissiveIntensity: 1.3 }); for (const side of [-1, 1]) { rock(g, side * 1.05, 1, 0, .6, c, 4); mesh(g, new THREE.ConeGeometry(.25, .9, 5), 0xdec0a1, side * .48, 2.3, 0); } }
    if (state.map === 3) { sphere(g, 0, 1.5, 0, .7, 0x947a92).scale.set(.6, 1.5, .7); for (const side of [-1, 1]) for (let i = 0; i < 2; i++) { const wing = sphere(g, side * 1.1, 1.9, i * .8 - .4, 1.2, i ? 0xe3c798 : 0xcdb4b1); wing.scale.set(1, .1, .7); wing.rotation.z = side * .35; crystal(g, side * 1.4, 2.1, i * .8 - .4, .24, 0xf3e4aa); } }
    if (state.map === 4) { crystal(g, 0, 1.8, 0, 1, 0xcbafea); for (let i = 0; i < 3; i++) { const orbit = mesh(g, new THREE.TorusGeometry(1.45 + i * .15, .075, 6, 36), 0xcbbddd, 0, 1.8, 0, { metalness: .6 }); orbit.rotation.set(i * .8, i * 1.1, .4); } }
    label(g, MAPS[state.map].boss, 0, 4.3, 0, { color: '#ffdbb2', size: .6 });
  }
  if (e.elite) { ring(g, .9, .06, 0xeac882, .12); g.scale.setScalar(1.3); }
  const health = box(g, 0, e.kind === 'boss' ? 3.8 : e.kind === 'brute' ? 2.15 : 1.65, 0, e.kind === 'boss' ? 2.8 : .9, .07, .09, 0xf0b18e, { emissive: 0x9e694e }); g.userData.health = health; return g;
}
function remove(obj) { obj.parent?.remove(obj); clearGroup(obj); if (obj.geometry) obj.geometry.dispose(); if (obj.material) obj.material.dispose(); }
function sync(key, items, create, update) { const alive = new Set(); for (const item of items) { const id = `${key}:${item.id}`; alive.add(id); let obj = cache.get(id); if (!obj) { obj = create(item); entities.add(obj); cache.set(id, obj); } update(obj, item); } for (const [id, obj] of cache) if (id.startsWith(key + ':') && !alive.has(id)) { remove(obj); cache.delete(id); } }
function createEffect(e) {
  const g = new THREE.Group();
  if (e.kind === 'line') { const a = new THREE.Vector3(e.x, 1, e.z), b = new THREE.Vector3(e.toX, 1, e.toZ); const line = branch(g, a, b, .035, e.color); line.material.emissive.setHex(e.color); line.material.emissiveIntensity = .8; }
  else if (e.kind === 'cone') { const fan = mesh(g, new THREE.CircleGeometry(e.radius, 24, (e.angle || 0) - .9, 1.8), e.color, e.x, .25, e.z, { transparent: true, opacity: .4, side: THREE.DoubleSide, depthWrite: false }); fan.rotation.x = Math.PI / 2; }
  else { g.position.set(e.x, .2, e.z); ring(g, 1, e.kind === 'orbit' ? .055 : .07, e.color); if (e.kind === 'burst') for (let i = 0; i < 6; i++) crystal(g, Math.cos(i) * .5, .3, Math.sin(i) * .5, .1, e.color); }
  return g;
}
function render(dt) {
  const p = state.player, t = state.time; hero.position.set(p.x, .12 + (p.dash > 0 ? .08 : 0), p.z); hero.rotation.y = Math.atan2(p.facingX, p.facingZ); hero.visible = p.invulnerable <= 0 || Math.floor(t * 18) % 2 === 0;
  hero.userData.feet.forEach((foot, i) => { foot.position.y = .18 + Math.max(0, Math.sin(t * 12 + i * Math.PI)) * .1 * (Math.abs(game.input.axis('x')) + Math.abs(game.input.axis('y'))); });
  for (const o of ornaments) { if (o.type === 'lava') o.mesh.material.emissiveIntensity = t % 8 > 5 ? 1.5 : .3; if (o.type === 'crystal') { o.mesh.rotation.y = t * .3; o.mesh.position.y = 1.6 + Math.sin(t + o.mesh.position.x) * .15; } if (o.type === 'water') o.mesh.material.opacity = .55 + Math.sin(t * 2) * .08; if (o.type === 'motes') o.mesh.rotation.y = t * .008; if (o.type === 'pulse') { o.mesh.material.emissiveIntensity = t % 12 > 10.5 ? 1.8 : .1; o.mesh.scale.setScalar(t % 12 > 10.5 ? 1.02 : 1); } }
  sync('enemy', state.enemies, makeEnemy, (obj, e) => { obj.position.set(e.x, .12 + (e.kind === 'moth' || e.kind === 'spitter' ? Math.sin(t * 3 + e.id) * .12 : Math.sin(t * 7 + e.id) * .025), e.z); obj.rotation.y = Math.atan2(p.x - e.x, p.z - e.z); obj.userData.health.scale.x = Math.max(.01, e.hp / e.maxHp); obj.userData.health.visible = e.hp < e.maxHp || e.kind === 'boss'; });
  sync('shot', state.projectiles, e => { const g = new THREE.Group(); const m = crystal(g, 0, .8, 0, e.kind === 'spear' ? .2 : .13, e.color || 0xbdf2d3); m.rotation.z = Math.PI / 2; return g; }, (obj, e) => { obj.position.set(e.x, .15, e.z); obj.rotation.y = Math.atan2(e.vx, e.vz); });
  sync('enemyShot', state.enemyShots, () => { const g = new THREE.Group(); sphere(g, 0, .8, 0, .21, 0xf4a17f, { emissive: 0xe98062, emissiveIntensity: .65 }); return g; }, (obj, e) => obj.position.set(e.x, .1, e.z));
  sync('gem', state.gems, e => { const g = new THREE.Group(); crystal(g, 0, .35, 0, e.value >= 10 ? .22 : .13, e.value >= 10 ? 0xffd79b : 0x85e5bd); return g; }, (obj, e) => { obj.position.set(e.x, .08 + Math.sin(t * 2 + e.id) * .07, e.z); obj.rotation.y = t; });
  sync('field', state.fields, e => { const g = new THREE.Group(); ring(g, e.radius, .05, e.color, .19); if (e.kind === 'thorn') for (let i = 0; i < 7; i++) { const thorn = mesh(g, new THREE.ConeGeometry(.13, .7, 4), 0x9ac184, Math.cos(i) * e.radius * .7, .35, Math.sin(i) * e.radius * .7); thorn.rotation.z = .3; } else rock(g, 0, 5, 0, .7, 0xe0b087, 3); return g; }, (obj, e) => { obj.position.set(e.x, .1, e.z); if (e.kind === 'meteor' && obj.children[1]) obj.children[1].position.y = Math.max(.25, e.tick * 8); });
  sync('effect', state.effects, createEffect, (obj, e) => { const life = e.ttl / e.life; if (!['line', 'cone'].includes(e.kind)) obj.scale.setScalar(e.radius * (1.15 - life * .3)); obj.traverse(m => { if (m.material) { m.material.transparent = true; m.material.opacity = life * .75; m.material.depthWrite = false; } }); });
  const narrow = game.camera.aspect < .85, height = narrow ? 33 : 27, distance = narrow ? 26 : 21, follow = narrow ? .86 : .35;
  const target = new THREE.Vector3(p.x * follow, height, p.z * follow + distance); game.camera.position.lerp(target, Math.min(1, dt * 4)); game.camera.lookAt(p.x * follow, 0, p.z * follow - 1.5);
  game.ui.stats([{ label: '生命', value: `${Math.ceil(p.hp)} / ${p.maxHp}` }, { label: '微光等级', value: state.level }, { label: '守夜', value: `${Math.floor(t)} / ${MAPS[state.map].duration}s` }, { label: '击败', value: state.kills }]);
  xp.firstElementChild.style.width = `${Math.min(100, state.xp / state.needed * 100)}%`;
  const signature = JSON.stringify(state.weapons.map(w => [w.id, w.rank, w.evolved])); if (signature !== shownLoadout) { shownLoadout = signature; loadout.innerHTML = state.weapons.map(w => { const def = WEAPONS.find(x => x.id === w.id); return `<span>${w.evolved ? '<em>✦ ' + def.evolution + '</em>' : def.name + ' ' + '·'.repeat(w.rank)}</span>`; }).join(''); }
  game.ui.hint(`WASD 移动 · 自动攻击 · 冲刺 ${p.dashCooldown > 0 ? p.dashCooldown.toFixed(1) + 's' : '就绪'} · ${state.bossSpawned && !state.bossDefeated ? '击败 ' + MAPS[state.map].boss : '收集结晶，组合武器与媒介'}`);
}
function start() { state = createRun({ map: selectedMap, character: selectedCharacter, save }); lastPhase = ''; shownLoadout = ''; buildWorld(); game.camera.position.set(0, 29, 24); render(.04); game.ui.hideOverlay(); }
function menu() {
  game.ui.overlay({ title: '将最后一盏灯，带到黎明。', text: '移动避敌 · 自动攻击 · 六件武器构筑 · 三分钟一场守夜', body: `<div class="run-intro">林间的微光还未熄灭。<br>选一位同行者，走进下一片长夜。</div><div class="field"><label for="map-choice">守夜之地</label><select id="map-choice">${MAPS.map((m, i) => `<option value="${i}" ${i === selectedMap ? 'selected' : ''}>${m.name} · 最长 ${save.best[i]}s</option>`).join('')}</select></div><p id="map-summary" class="muted map-summary">${MAPS[selectedMap].detail}</p><p class="section-label">同行者 · 六种起始构筑</p><div class="choice-grid">${CHARACTERS.map((c, i) => `<button class="choice ${i === selectedCharacter ? 'selected' : ''}" data-character="${i}"><strong>${c.name}</strong><small>${WEAPONS.find(w => w.id === c.weapon).name}<br>${c.passive}</small></button>`).join('')}</div><p class="muted">萤石 ${save.shards} · 生命研习 ${save.vitality}/10 · 伤害研习 ${save.power}/10 · 胜场 ${save.wins}</p>`, buttons: [{ label: '踏入长夜', primary: true, onClick: () => { selectedMap = Number(document.querySelector('#map-choice').value); start(); } }, ...(state && ['playing', 'upgrade'].includes(state.phase) ? [{ label: '继续本局', onClick: () => { selectedMap = state.map; selectedCharacter = state.character; if (state.phase === 'upgrade') upgradeMenu(); else game.ui.hideOverlay(); } }] : []), { label: '萤石研习', onClick: growthMenu }, { label: '武器图鉴', onClick: codexMenu }] });
  document.querySelector('#map-choice').addEventListener('change', e => { selectedMap = Number(e.target.value); document.querySelector('#map-summary').textContent = MAPS[selectedMap].detail; });
  document.querySelectorAll('[data-character]').forEach(button => button.addEventListener('click', () => { selectedCharacter = Number(button.dataset.character); document.querySelectorAll('[data-character]').forEach(b => b.classList.toggle('selected', b === button)); }));
}
function growthMenu() { game.ui.overlay({ title: '萤石研习', text: `持有 ${save.shards} 萤石。每局结算都会留下进步。`, body: `<div class="choice-grid"><div class="choice"><strong>生命研习 ${save.vitality}/10</strong><small>每级增加 5 起始生命</small></div><div class="choice"><strong>伤害研习 ${save.power}/10</strong><small>每级增加 4% 武器伤害</small></div></div>`, buttons: [{ label: `生命 · ${30 + save.vitality * 25} 萤石`, disabled: save.vitality >= 10, onClick: () => purchase('vitality') }, { label: `伤害 · ${30 + save.power * 25} 萤石`, disabled: save.power >= 10, onClick: () => purchase('power') }, { label: '返回', onClick: menu }] }); }
function purchase(key) { const next = buyGrowth(save, key); if (!next) game.ui.toast('萤石不足，完成守夜后再来。'); else { save = next; game.save(save); growthMenu(); } }
function codexMenu() { game.ui.overlay({ title: '十二件微光遗物', text: '武器升至四级，并持有一份对应媒介，即刻进化。最多同时持有六件武器。', body: `<div class="codex-entry">${WEAPONS.map(w => `<article><strong>${w.name} → ${w.evolution}</strong><p>${w.desc}<br>进化媒介：${PASSIVES.find(p => p.id === w.catalyst).name}</p></article>`).join('')}</div>`, buttons: [{ label: '返回选角', primary: true, onClick: menu }] }); }
function upgradeMenu() { game.ui.overlay({ title: `微光生长 · 等级 ${state.level}`, text: '从三份回响中选择一份。选择期间，长夜静止。', body: `<div class="choice-grid">${state.choices.map(c => `<button class="choice" data-upgrade="${c.id}"><strong>${c.name}</strong><small>${c.desc}</small></button>`).join('')}</div>`, buttons: [] }); document.querySelectorAll('[data-upgrade]').forEach(button => button.addEventListener('click', () => { chooseUpgrade(state, button.dataset.upgrade); for (const event of state.events) if (event.type === 'evolve') game.ui.toast('武器进化：' + event.name); lastPhase = ''; if (state.phase === 'upgrade') upgradeMenu(); else game.ui.hideOverlay(); })); }
function finish() { const before = save.shards; save = settleRun(state, save); game.save(save); game.ui.overlay({ title: state.phase === 'won' ? '黎明已至，微光长存。' : '灯会熄灭，回响会留下。', text: `${MAPS[state.map].name} · 守夜 ${Math.floor(state.time)} 秒 · 击败 ${state.kills} · 等级 ${state.level}\n本次获得 ${save.shards - before} 萤石`, body: `<p class="muted">${state.phase === 'won' ? '你守住了这片土地。换一位同行者，尝试新的武器构筑。' : '多留出转身空间，冲刺穿过包围。四级武器搭配媒介，可改变战局。'}</p>`, buttons: [{ label: '再次守夜', primary: true, onClick: start }, { label: '返回选角', onClick: menu }, { label: '萤石研习', onClick: growthMenu }] }); }
game.onMenu(menu);
state = createRun(); buildWorld(); render(.04); menu();
game.run(dt => {
  stepRun(state, { x: game.input.axis('x'), z: game.input.axis('y'), dash: game.input.pressed('Space') }, dt); render(dt);
  for (const event of state.events) { if (event.type === 'hurt') game.sound(115, .15, 'triangle'); if (event.type === 'boss') game.ui.toast(`${event.name} 苏醒了`); if (event.type === 'elite') game.ui.toast('精英已出现 · 击败它获取大量经验'); if (event.type === 'attack' && state.time - lastSound > .18) { game.sound(400 + state.level * 12, .055, 'sine', .016); lastSound = state.time; } }
  if (state.phase !== lastPhase) { lastPhase = state.phase; if (state.phase === 'upgrade') upgradeMenu(); else if (state.phase === 'won' || state.phase === 'lost') finish(); }
});
