import { THREE, createGame, box, sphere, cylinder, label, clearGroup } from '../arcade-runtime/runtime.mjs';
import { REGIONS, NIGHTS, RECIPES, BUILDINGS, PLOTS, createExpedition, stepExpedition, craft, build, upgradeBuilding, repairBuilding, beginNight, sanitizeSave, settleExpedition, buyMastery } from './core.mjs';
const game = createGame({ id: 'nightfall-camp', title: '夜幕营地', subtitle: 'NIGHTFALL / KEEP THE FIRE', accent: '#e9cda0', background: 0x344b43, help: 'WASD / 方向键移动。靠近资源按住 E 采集；靠近篝火按 E 添加木柴并修复。Space 挥矛，面向敌人攻击。Q 制造，B 营建，N 提前开始夜晚。第 3、6、9、12 天出现求救者，靠近 E 护送回营。第 10 夜起可造信标；守过 15 夜、救回 3 人并建信标即可撤离。P / Esc 暂停，手机使用底部操作钮。' });
game.controls([{ code: 'KeyE', label: '采集' }, { code: 'Space', label: '挥矛' }, { code: 'KeyQ', label: '制造' }]);
let save = sanitizeSave(game.load(null)), state, selectedRegion = 0, endless = false, world, units, hero, fireModel, fireLight, marker, selectedPlot = 0, lastPhase = '', lastSound = 0, resourceSignature = '';
const cache = new Map(), nodeModels = new Map(), sceneryItems = [];
const resourceNames = { wood: '木材', stone: '石料', food: '食物', ore: '矿石', crystal: '晶体' }, resourceColors = { wood: 0xa88c66, stone: 0xb4b9ac, food: 0xc68d81, ore: 0xc4b785, crystal: 0xc7b2dd };
const resources = document.createElement('div'); resources.className = 'camp-resources'; document.body.append(resources);
const context = document.createElement('div'); context.className = 'camp-context'; document.body.append(context);
const dock = document.createElement('div'); dock.className = 'camp-dock'; dock.innerHTML = '<button class="craft-button">制造 · Q</button><button class="build-button">营建 · B</button><button class="night-button">开始守夜 · N</button>'; document.body.append(dock);
const mat = (color, opts = {}) => new THREE.MeshStandardMaterial({ color, roughness: .83, metalness: .04, ...opts });
function mesh(parent, geo, color, x = 0, y = 0, z = 0, opts = {}) { const m = new THREE.Mesh(geo, mat(color, opts)); m.position.set(x, y, z); m.castShadow = true; m.receiveShadow = true; parent.add(m); return m; }
function ring(parent, radius, tube, color, y = 0) { const m = mesh(parent, new THREE.TorusGeometry(radius, tube, 6, 36), color, 0, y, 0, { emissive: color, emissiveIntensity: .12 }); m.rotation.x = Math.PI / 2; return m; }
function rod(parent, a, b, r, color) { const delta = new THREE.Vector3().subVectors(b, a); const m = cylinder(parent, 0, 0, 0, r, r * 1.1, delta.length(), color, { segments: 7 }); m.position.copy(a).add(b).multiplyScalar(.5); m.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), delta.normalize()); return m; }
function rock(parent, x, y, z, size, color, i = 0) { const r = mesh(parent, new THREE.DodecahedronGeometry(size, 0), color, x, y, z); r.scale.set(1.1, .75, .83); r.rotation.set(i * .23, i * .6, i * .11); return r; }
function gem(parent, x, y, z, size, color) { const g = mesh(parent, new THREE.OctahedronGeometry(size, 0), color, x, y, z, { roughness: .25, metalness: .25, emissive: color, emissiveIntensity: .22 }); g.scale.y = 1.6; return g; }
function pine(parent, x, z, scale, snow = false) { const g = new THREE.Group(); parent.add(g); g.position.set(x, 0, z); g.scale.setScalar(scale); cylinder(g, 0, 1.2, 0, .15, .28, 2.4, 0x87755b, { segments: 7 }); for (let i = 0; i < 3; i++) { const leaves = mesh(g, new THREE.ConeGeometry(1.05 - i * .2, 1.9 - i * .15, 7), snow && i % 2 === 0 ? 0xc6d2c8 : [0x607e64, 0x769275, 0x8c9f7c][i], 0, 1.8 + i * .65, 0); leaves.rotation.y = i * .3; } return g; }
function tent(parent, x, z, scale = 1, color = 0xcfba94) { const g = new THREE.Group(); parent.add(g); g.position.set(x, 0, z); g.scale.setScalar(scale); const geometry = new THREE.BufferGeometry(); const vertices = [-1, 0, -.9, 0, 1.6, -.9, -1, 0, .9, 0, 1.6, -.9, 0, 1.6, .9, -1, 0, .9, 0, 1.6, -.9, 1, 0, -.9, 1, 0, .9, 0, 1.6, -.9, 1, 0, .9, 0, 1.6, .9]; geometry.setAttribute('position', new THREE.Float32BufferAttribute(vertices, 3)); geometry.computeVertexNormals(); mesh(g, geometry, color, 0, .06, 0, { side: THREE.DoubleSide }); rod(g, new THREE.Vector3(0, .1, -1), new THREE.Vector3(0, 1.9, -1), .04, 0x83745b); rod(g, new THREE.Vector3(0, .1, 1), new THREE.Vector3(0, 1.9, 1), .04, 0x83745b); rod(g, new THREE.Vector3(0, 1.65, -1.7), new THREE.Vector3(0, 1.65, 1.7), .05, 0x83745b); for (const side of [-1, 1]) for (const end of [-1, 1]) rod(g, new THREE.Vector3(side * .9, .25, end * .9), new THREE.Vector3(side * 1.3, .05, end * 1.35), .015, 0xd4c8aa); return g; }
function makeNode(node) {
  const g = new THREE.Group(), harvest = new THREE.Group(); g.add(harvest); g.position.set(node.x, .1, node.z);
  if (node.resource === 'wood') { cylinder(g, 0, .2, 0, .23, .34, .4, 0xab9471, { segments: 7 }); pine(harvest, 0, 0, .9 + node.id % 3 * .12, state.region === 2); }
  if (node.resource === 'stone' || node.resource === 'ore') { rock(g, 0, .2, 0, .65, 0x747e78, node.id); for (let i = 0; i < 3; i++) rock(harvest, Math.cos(i * 2.1) * .35, .5 + i * .13, Math.sin(i * 2.1) * .3, .58, node.resource === 'ore' ? 0x8d8980 : 0xacb3a6, node.id + i); if (node.resource === 'ore') for (let i = 0; i < 4; i++) gem(harvest, Math.cos(i) * .45, .7, Math.sin(i) * .45, .18, 0xd8c492); }
  if (node.resource === 'food') { for (let i = 0; i < 4; i++) { const b = sphere(harvest, Math.cos(i * 1.57) * .35, .48, Math.sin(i * 1.57) * .35, .5, 0x718e65); b.scale.y = .85; for (let j = 0; j < 3; j++) sphere(harvest, Math.cos(i + j) * .52, .6 + j * .12, Math.sin(i + j) * .52, .09, j % 2 ? 0xd9a394 : 0xa96666); } }
  if (node.resource === 'crystal') { rock(g, 0, .15, 0, .6, 0x7b7f83, node.id); for (let i = 0; i < 4; i++) { const c = gem(harvest, Math.cos(i) * .35, .55 + i % 2 * .25, Math.sin(i) * .35, .26 + i % 2 * .1, 0xcbb6e1); c.rotation.z = Math.cos(i) * .3; } }
  g.userData.harvest = harvest; return g;
}
function scenery() {
  clearGroup(game.world); cache.clear(); nodeModels.clear(); sceneryItems.length = 0; world = new THREE.Group(); units = new THREE.Group(); game.world.add(world, units);
  cylinder(world, 0, -.8, 0, 18, 17, 1.5, [0x3e5244, 0x394c4b, 0x5c6570][state.region], { segments: 80 }); cylinder(world, 0, -.04, 0, 17.7, 18, .4, REGIONS[state.region].color, { segments: 80 }); ring(world, 17.65, .09, 0x7e9079, .1);
  cylinder(world, 0, .16, 0, 4.2, 4.3, .13, [0x9f9476, 0x9a987b, 0xa7a89a][state.region], { segments: 48 });
  for (let i = 0; i < 90; i++) { const angle = i * 2.399, r = 4.4 + Math.sqrt((i * 79) % 997 / 997) * 12.7, x = Math.cos(angle) * r, z = Math.sin(angle) * r; if (state.nodes.some(n => Math.hypot(x - n.x, z - n.z) < 1.1)) continue; if (i % 3 === 0) rock(world, x, .06, z, .2 + i % 4 * .04, state.region === 2 ? 0xcbd1c8 : 0x7b8d6e, i); else for (let j = 0; j < 3; j++) { const grass = mesh(world, new THREE.ConeGeometry(.035, .35, 3), state.region === 1 ? 0xa2b5a4 : 0x98a47f, x + j * .09, .22, z); grass.rotation.z = j * .2; } }
  if (state.region === 1) for (let i = 0; i < 8; i++) { const x = Math.sin(i * 2.3) * 11, z = Math.cos(i * 1.8) * 11; if (Math.hypot(x, z) < 6) continue; const pool = cylinder(world, x, .19, z, 2, 2, .025, 0x4b7e80, { opacity: .55 }); pool.scale.set(1.5, 1, .8); sceneryItems.push({ type: 'water', mesh: pool }); }
  for (const node of state.nodes) { const model = makeNode(node); world.add(model); nodeModels.set(node.id, model); }
  for (let i = 0; i < 24; i++) { const a = i / 24 * Math.PI * 2; if (i % 3 === 0) pine(world, Math.cos(a) * 17.9, Math.sin(a) * 17.9, 1 + i % 4 * .08, state.region === 2); else rock(world, Math.cos(a) * 17.9, -.1, Math.sin(a) * 17.9, .8, state.region === 2 ? 0xaab3af : 0x596952, i); }
  tent(world, -2.4, -2, .95); const supplies = new THREE.Group(); supplies.position.set(2.3, .15, -2.2); world.add(supplies); for (let i = 0; i < 3; i++) { const sack = sphere(supplies, (i - 1) * .5, .3, i % 2 * .4, .34, 0xc3b68c); sack.scale.y = 1.2; ring(supplies, .11, .018, 0x8e866a, .66).position.x = (i - 1) * .5; } box(supplies, 0, .7, -.6, 1.5, .12, .8, 0x8e7a5b); for (const side of [-1, 1]) box(supplies, side * .5, .4, -.6, .12, .7, .12, 0x786b55);
  fireModel = new THREE.Group(); world.add(fireModel); fireModel.position.y = .18; for (let i = 0; i < 9; i++) rock(fireModel, Math.cos(i / 9 * Math.PI * 2) * .8, .1, Math.sin(i / 9 * Math.PI * 2) * .8, .28, 0xbbb5a1, i); for (let i = 0; i < 4; i++) { const log = cylinder(fireModel, 0, .17, 0, .12, .14, 1.25, 0x7a5f42, { segments: 7 }); log.rotation.set(Math.PI / 2, i * Math.PI / 4, 0); } const flames = new THREE.Group(); fireModel.add(flames); for (let i = 0; i < 5; i++) { const f = mesh(flames, new THREE.ConeGeometry(.2 + i % 2 * .09, .8 + i % 3 * .22, 6), i % 2 ? 0xffd796 : 0xf2a364, Math.cos(i * 2.399) * .2, .55 + i % 2 * .2, Math.sin(i * 2.399) * .2, { emissive: i % 2 ? 0xffc574 : 0xf07c35, emissiveIntensity: .9 }); f.rotation.z = .15; } fireModel.userData.flames = flames;
  fireLight = new THREE.PointLight(0xffbc75, 2, 18, 1.8); fireLight.position.set(0, 2.2, 0); world.add(fireLight);
  for (const [i, p] of PLOTS.entries()) { const g = new THREE.Group(); world.add(g); g.position.set(p.x, .18, p.z); ring(g, .82, .04, 0xb8b497, .05); for (const side of [-1, 1]) { cylinder(g, side * .68, .25, .5, .04, .06, .5, 0xac9571); cylinder(g, side * .68, .25, -.5, .04, .06, .5, 0xac9571); } label(g, String(i + 1), 0, .55, 0, { size: .36, color: '#e2d7ae' }); }
  marker = new THREE.Group(); ring(marker, 1.1, .06, 0xf5dc9c, .2); world.add(marker);
  hero = makePerson(false); units.add(hero); label(world, '守住这盏火', 0, 3, -1.2, { size: .47, color: '#ffdfa6' });
  const pos = []; for (let i = 0; i < 70; i++) pos.push(Math.cos(i * 2.399) * (2 + i % 15), .7 + i % 5 * .55, Math.sin(i * 2.399) * (2 + i % 15)); const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); const motes = new THREE.Points(geometry, new THREE.PointsMaterial({ color: 0xe5ddb0, size: .055, opacity: .65, transparent: true, depthWrite: false })); world.add(motes); sceneryItems.push({ type: 'motes', mesh: motes });
}
function makePerson(survivor = false) { const g = new THREE.Group(), coat = survivor ? 0xbaa9a0 : 0xbc9272; cylinder(g, 0, .73, 0, .29, .37, .86, coat, { segments: 8 }); sphere(g, 0, 1.36, 0, .28, 0xe3c9a4); const cap = sphere(g, 0, 1.54, -.03, .31, survivor ? 0x8c9e99 : 0x697968); cap.scale.y = .47; cylinder(g, 0, 1.47, .02, .4, .4, .05, survivor ? 0x8c9e99 : 0x697968); for (const side of [-1, 1]) { sphere(g, side * .095, 1.37, .245, .025, 0x394843); cylinder(g, side * .37, .81, 0, .1, .11, .6, coat, { segments: 7 }); const boot = sphere(g, side * .18, .19, .08, .18, 0x596055); boot.scale.set(.75, .8, 1.2); } if (!survivor) { box(g, 0, .86, -.29, .54, .64, .27, 0x77836b); const spear = new THREE.Group(); g.add(spear); spear.position.set(.45, .65, .24); cylinder(spear, 0, .4, 0, .03, .04, 1.9, 0xc0a579, { segments: 6 }); mesh(spear, new THREE.ConeGeometry(.12, .4, 4), 0xcfd6cd, 0, 1.48, 0); g.userData.spear = spear; } return g; }
function makeBuilding(b) {
  const def = BUILDINGS.find(x => x.id === b.type), g = new THREE.Group(); g.userData.signature = `${b.type}:${b.level}`;
  if (b.type === 'barricade') { for (let i = 0; i < 5; i++) { const x = (i - 2) * .37, log = cylinder(g, x, .55, 0, .09, .13, 1.3 + i % 2 * .2, 0xb1986d, { segments: 6 }); log.rotation.z = (i - 2) * .1; mesh(g, new THREE.ConeGeometry(.1, .25, 6), 0xd0bb8f, x, 1.32 + i % 2 * .1, 0); } rod(g, new THREE.Vector3(-.95, .5, .15), new THREE.Vector3(.95, .5, .15), .08, 0x807355); }
  if (b.type === 'turret') { for (const x of [-.55, .55]) for (const z of [-.55, .55]) { cylinder(g, x, .8, z, .07, .13, 1.6, 0xa48d67, { segments: 7 }); } box(g, 0, 1.65, 0, 1.5, .14, 1.35, 0xb49c73); const head = new THREE.Group(); g.add(head); head.position.y = 1.75; const bow = mesh(head, new THREE.TorusGeometry(.5, .06, 6, 20, Math.PI), 0xd6bb89, 0, .37, .1); bow.rotation.z = Math.PI; rod(head, new THREE.Vector3(-.5, .37, .1), new THREE.Vector3(.5, .37, .1), .015, 0xddcfaa); const shaft = cylinder(head, 0, .35, .3, .04, .04, 1.2, 0x6c7769); shaft.rotation.x = Math.PI / 2; g.userData.head = head; }
  if (b.type === 'garden') { box(g, 0, .13, 0, 1.8, .25, 1.6, 0x716b4e); for (const side of [-1, 1]) { box(g, side * .92, .2, 0, .1, .3, 1.9, 0xa99976); box(g, 0, .2, side * .84, 1.9, .3, .1, 0xa99976); } for (let i = 0; i < 9; i++) { const x = (i % 3 - 1) * .5, z = (Math.floor(i / 3) - 1) * .45; const leaf = sphere(g, x, .4, z, .25, i % 2 ? 0xa5b879 : 0x78956a); leaf.scale.set(.7, .35, 1); sphere(g, x, .41, z, .075, 0xd9c495); } }
  if (b.type === 'collector') { cylinder(g, 0, .55, 0, .5, .45, 1.1, 0xa2b9b1, { segments: 10 }); const basin = cylinder(g, 0, 1.14, 0, .78, .48, .35, 0xbbd2c6, { segments: 14 }); cylinder(g, 0, 1.33, 0, .67, .67, .025, 0x7faeb4, { opacity: .7 }); rod(g, new THREE.Vector3(.7, .2, .4), new THREE.Vector3(.7, 2, .4), .04, 0x8d9c91); box(g, .7, 1.9, .05, .65, .06, 1, 0xd4d0ae).rotation.x = -.15; }
  if (b.type === 'infirmary') { tent(g, 0, 0, .85, 0xded3b5); box(g, 0, 1, .81, .4, .12, .04, 0x91a592); box(g, 0, 1, .81, .12, .4, .04, 0x91a592); }
  if (b.type === 'kiln') { const dome = sphere(g, 0, .45, 0, .86, 0x9e8e77); dome.scale.y = .82; cylinder(g, .3, 1.25, -.2, .22, .3, 1, 0x7f7d71, { segments: 9 }); const mouth = mesh(g, new THREE.CircleGeometry(.36, 20), 0x453f35, 0, .38, .79); sphere(g, 0, .3, .8, .2, 0xf4bd73, { emissive: 0xea903e }); }
  if (b.level > 1) for (let i = 0; i < b.level; i++) gem(g, (i - (b.level - 1) / 2) * .24, .35, .85, .09, 0xe2d0a3);
  const hp = box(g, 0, b.type === 'turret' ? 2.6 : 1.9, 0, 1.5, .06, .07, 0xe9cd95); g.userData.hp = hp; return g;
}
function makeEnemy(e) {
  const g = new THREE.Group(), color = { wolf: 0x989994, raider: 0x9b9185, spitter: 0x9aa888, brute: 0x8f877e, shade: 0x9990a8, boss: 0x9d8a80 }[e.kind];
  if (e.kind === 'wolf' || e.kind === 'brute' || e.kind === 'boss') { const size = e.kind === 'boss' ? 1.3 : e.kind === 'brute' ? 1 : .7, body = sphere(g, 0, .65, 0, size, color); body.scale.set(.6, .65, 1.05); const head = sphere(g, 0, .78, size * .9, size * .46, color); head.scale.set(.85, .75, 1.2); for (const side of [-1, 1]) { for (const z of [-size * .55, size * .55]) cylinder(g, side * size * .42, .26, z, .07 * size + .035, .1 * size + .02, .52, color, { segments: 6 }); mesh(g, new THREE.ConeGeometry(size * .14, size * .48, 4), 0xc1b8a5, side * size * .28, 1.1 + size * .1, size * .77); sphere(g, side * size * .19, .84, size * 1.28, .04 + size * .02, 0xeac196, { emissive: 0xe09364 }); if (e.kind !== 'wolf') { const tusk = mesh(g, new THREE.ConeGeometry(.12, .6, 5), 0xdccbb0, side * size * .32, .48, size * 1.18); tusk.rotation.x = -.6; } } const tail = mesh(g, new THREE.ConeGeometry(.12, size, 5), color, 0, .7, -size); tail.rotation.x = -1; if (e.kind === 'boss') { ring(g, 1.6, .055, 0xdaaf8e, .1); for (let i = 0; i < 4; i++) gem(g, 0, 1.1 + Math.sin(i) * .2, (i - 1.5) * .6, .22, 0xbc9ab6); } }
  else if (e.kind === 'spitter') { sphere(g, 0, .65, 0, .55, color).scale.set(.9, .6, 1.15); for (let i = 0; i < 5; i++) { const petal = sphere(g, Math.cos(i) * .4, .8, Math.sin(i) * .4, .26, 0xb9b497); petal.scale.y = .3; } sphere(g, 0, .75, .57, .2, 0xbc9db3, { emissive: 0x895f80 }); }
  else { cylinder(g, 0, .76, 0, .25, .4, 1.1, color, { segments: 7 }); sphere(g, 0, 1.35, .05, .28, 0xc2bcb0); for (const side of [-1, 1]) { const arm = cylinder(g, side * .37, .95, 0, .075, .11, .8, color, { segments: 6 }); arm.rotation.z = side * .45; sphere(g, side * .1, 1.37, .3, .04, 0xe0b297, { emissive: 0xba7967 }); } if (e.kind === 'shade') { const hood = mesh(g, new THREE.ConeGeometry(.48, .6, 6), 0xb1a3ba, 0, 1.7, -.1); hood.rotation.z = -.2; } }
  const hp = box(g, 0, e.kind === 'boss' ? 2.25 : 1.85, 0, e.kind === 'boss' ? 2.2 : .9, .055, .07, 0xe6b19a); g.userData.hp = hp; return g;
}
function remove(obj) { obj.parent?.remove(obj); clearGroup(obj); }
function sync(prefix, items, create, update, signature = null) { const seen = new Set(); for (const item of items) { const id = `${prefix}:${item.id}`; seen.add(id); let obj = cache.get(id); if (obj && signature && obj.userData.signature !== signature(item)) { remove(obj); cache.delete(id); obj = null; } if (!obj) { obj = create(item); units.add(obj); cache.set(id, obj); } update(obj, item); } for (const [id, obj] of cache) if (id.startsWith(prefix + ':') && !seen.has(id)) { remove(obj); cache.delete(id); } }
function effectMesh(e) { const g = new THREE.Group(); if (e.kind === 'line') rod(g, new THREE.Vector3(e.x, 2.1, e.z), new THREE.Vector3(e.toX, .8, e.toZ), .03, e.color); else if (e.kind === 'swing') { const arc = mesh(g, new THREE.TorusGeometry(e.radius, .045, 6, 20, Math.PI * 1.2), e.color, e.x, .85, e.z, { emissive: e.color, emissiveIntensity: .6 }); arc.rotation.set(Math.PI / 2, 0, -(e.angle || 0) - Math.PI * .6); } else { g.position.set(e.x, .18, e.z); ring(g, 1, .05, e.color, .1); if (e.kind === 'gather' || e.kind === 'burst') for (let i = 0; i < 5; i++) rock(g, Math.cos(i) * .5, .2, Math.sin(i) * .5, .12, e.color, i); } return g; }
function closestResource() { return state.nodes.filter(n => n.amount > 0).sort((a, b) => Math.hypot(a.x - state.player.x, a.z - state.player.z) - Math.hypot(b.x - state.player.x, b.z - state.player.z))[0]; }
function render(dt) {
  const p = state.player, t = state.time, night = state.phase === 'night'; hero.position.set(p.x, .18, p.z); hero.rotation.y = Math.atan2(p.facingX, p.facingZ); hero.visible = p.invulnerable <= 0 || Math.floor(t * 14) % 2 === 0; hero.userData.spear.rotation.x = p.attackCooldown > .2 ? .9 + Math.sin((.48 - p.attackCooldown) * 11) * .8 : .15;
  const colors = night ? [0x172827, 0x18292f, 0x252b3c] : [0x3e5b4b, 0x425e5d, 0x626f80]; game.scene.background.lerp(new THREE.Color(colors[state.region]), Math.min(1, dt * .9)); game.scene.fog.color.copy(game.scene.background); game.sun.intensity += ((night ? .45 : 2.25) - game.sun.intensity) * Math.min(1, dt); game.sun.color.setHex(night ? 0x9bbfd0 : 0xffe6bd);
  fireLight.intensity = (night ? 4.2 : 1.2) * (.9 + Math.sin(t * 8) * .06) * Math.min(1, state.fire.fuel / 20); fireModel.userData.flames.scale.setScalar(Math.max(.08, Math.min(1, state.fire.fuel / 35))); fireModel.userData.flames.children.forEach((f, i) => { f.scale.y = .8 + Math.sin(t * (6 + i) + i) * .25; f.rotation.y = t + i; });
  for (const item of sceneryItems) { if (item.type === 'motes') item.mesh.rotation.y = t * .006; if (item.type === 'water') item.mesh.material.opacity = .48 + Math.sin(t * 2) * .05; }
  for (const node of state.nodes) nodeModels.get(node.id).userData.harvest.visible = node.amount > 0;
  sync('building', state.buildings, makeBuilding, (obj, b) => { obj.position.set(b.x, .28, b.z); obj.rotation.y = b.type === 'barricade' ? Math.atan2(b.x, b.z) : 0; if (obj.userData.head) obj.userData.head.rotation.y = b.angle || 0; obj.userData.hp.scale.x = Math.max(.01, b.hp / b.maxHp); obj.userData.hp.visible = b.hp < b.maxHp; }, b => `${b.type}:${b.level}`);
  sync('enemy', state.enemies, makeEnemy, (obj, e) => { const old = obj.position.clone(); obj.position.set(e.x, .17 + Math.sin(t * 6 + e.id) * .035, e.z); if (old.distanceTo(obj.position) > .004) obj.rotation.y = Math.atan2(e.x - old.x, e.z - old.z); obj.userData.hp.scale.x = Math.max(.01, e.hp / e.maxHp); obj.userData.hp.visible = e.hp < e.maxHp; });
  sync('survivor', state.survivors.filter(s => !s.rescued), () => { const g = makePerson(true); label(g, '求救 · E 护送', 0, 2.3, 0, { size: .35, color: '#f5dfaa' }); ring(g, 1, .04, 0xf5d895, .12); return g; }, (obj, s) => { obj.position.set(s.x, .2, s.z); if (s.following) obj.rotation.y = Math.atan2(p.x - s.x, p.z - s.z); });
  sync('projectile', state.projectiles, e => { const g = new THREE.Group(); sphere(g, 0, .85, 0, .18, e.color, { emissive: e.color }); return g; }, (obj, e) => obj.position.set(e.x, .1, e.z));
  sync('effect', state.effects, effectMesh, (obj, e) => { const life = e.ttl / e.life; if (!['line', 'swing'].includes(e.kind)) obj.scale.setScalar(e.radius * (1.25 - life * .35)); obj.traverse(m => { if (m.material) { m.material.transparent = true; m.material.opacity = life * .8; m.material.depthWrite = false; } }); });
  if (state.beacon && !cache.has('beacon')) { const g = new THREE.Group(); cylinder(g, 0, 1.1, -1.5, .16, .3, 2.2, 0x999980); gem(g, 0, 2.4, -1.5, .5, 0xe7d7a5); for (let i = 0; i < 3; i++) ring(g, .6 + i * .25, .035, 0xe3ca99, 2.4 + i * .18).position.z = -1.5; units.add(g); cache.set('beacon', g); }
  const nearest = closestResource(), close = nearest && Math.hypot(nearest.x - p.x, nearest.z - p.z) < 2, survivor = state.survivors.find(s => !s.rescued && !s.following && Math.hypot(s.x - p.x, s.z - p.z) < 2), fireNear = Math.hypot(p.x, p.z) < 2.6;
  marker.visible = Boolean(close || survivor || fireNear); const mark = survivor || (fireNear ? state.fire : nearest); if (mark) marker.position.set(mark.x, .1, mark.z);
  if (survivor) context.textContent = '发现失散者 · E 开始护送，带回篝火';
  else if (fireNear) context.textContent = state.fire.fuel >= 98 && state.fire.hp >= state.fire.maxHp ? '营火状况良好 · 走向林缘采集资源，准备下一夜' : state.resources.wood < 2 ? '添柴需要 2 木材 · 先去树旁按住 E 采集' : 'E 添柴修复 · 2 木材 → +28 燃料 / +12 耐久';
  else if (close) context.textContent = `按住 E 采集${resourceNames[nearest.resource]} · 剩余 ${nearest.amount}`;
  else { const signal = state.survivors.find(s => !s.rescued); if (signal) { const dx = signal.x - p.x, dz = signal.z - p.z; context.textContent = signal.following ? '失散者正在跟随 · 回到营火完成救援' : `求救信号：${dz > 2 ? '南' : dz < -2 ? '北' : ''}${dx > 2 ? '东' : dx < -2 ? '西' : ''}方 ${Math.round(Math.hypot(dx, dz))} 米`; } else context.textContent = night ? '守住营火 · Space 挥矛 · 岗楼自动射击' : `靠近树木、矿脉或浆果丛采集 · ${Math.ceil(Math.max(0, 42 - state.phaseTime))} 秒后入夜`; }
  const follow = game.camera.aspect < .85 ? .85 : .45, distance = game.camera.aspect < .85 ? 32 : 28;
  const target = new THREE.Vector3(p.x * follow, distance, p.z * follow + distance * .82); game.camera.position.lerp(target, Math.min(1, dt * 4)); game.camera.lookAt(p.x * follow, 0, p.z * follow - 1.2);
  game.ui.stats([{ label: '生命', value: Math.ceil(p.hp) }, { label: '营火耐久', value: Math.ceil(state.fire.hp) }, { label: '燃料', value: `${Math.ceil(state.fire.fuel)}%` }, { label: '饱腹', value: `${Math.ceil(p.hunger)}%` }, { label: night ? '守夜' : '白昼', value: `${state.night}${state.endless ? '' : ' / 15'}` }]);
  const signature = Object.values(state.resources).join(':'); if (signature !== resourceSignature) { resourceSignature = signature; resources.innerHTML = Object.entries(resourceNames).map(([key, name]) => `<span>${name}<b>${state.resources[key]}</b></span>`).join(''); }
  dock.querySelector('.night-button').disabled = state.phase !== 'day'; dock.querySelector('.night-button').textContent = night ? `夜袭 ${state.enemies.length + state.queue.length}` : '开始守夜 · N';
  game.ui.hint(`Q 制造 · B 营建 · 已救援 ${state.rescued}/3 · ${state.beacon ? '救援信标已点亮' : state.night >= 10 ? '可制造救援信标' : '第 10 夜解锁救援信标'}${state.fire.fuel < 20 ? ' · 燃料告急！' : ''}`);
}
const costText = cost => Object.entries(cost).map(([key, n]) => `${resourceNames[key]} ${n}`).join(' · ');
function inventoryHTML() { return `<div class="camp-summary">${Object.entries(resourceNames).map(([key, name]) => `<span>${name} ${state.resources[key]}</span>`).join('')}</div>`; }
function start() { state = createExpedition({ region: selectedRegion, endless, save }); lastPhase = ''; scenery(); game.camera.position.set(0, 29, 25); render(.05); game.ui.hideOverlay(); }
function menu() { game.ui.overlay({ title: '天黑之后，火就是家。', text: '采集 · 制造 · 营建 · 昼夜守卫 · 护送救援', body: `<p class="camp-story">白天为木柴走远一点，<br>夜里让每个人都能回到火边。</p><div class="field"><label for="region-choice">扎营区域</label><select id="region-choice">${REGIONS.map((r, i) => `<option value="${i}" ${i === selectedRegion ? 'selected' : ''}>${r.name} · 最佳 ${save.best[i]} 夜</option>`).join('')}</select></div><p class="muted" id="region-detail">${REGIONS[selectedRegion].desc}</p><div class="field"><label for="mode-choice">旅程</label><select id="mode-choice"><option value="campaign">十五夜救援 · 有明确撤离目标</option><option value="endless">无尽守卫 · 每夜继续变难</option></select></div><p class="muted">营地学识 ${save.knowledge} · 野外经验 ${save.mastery}/8 · 累计救援 ${save.rescues} · 已撤离 ${save.victories} 次</p>`, buttons: [{ label: '点燃营火', primary: true, onClick: () => { selectedRegion = Number(document.querySelector('#region-choice').value); endless = document.querySelector('#mode-choice').value === 'endless'; start(); } }, ...(state && ['day', 'night'].includes(state.phase) ? [{ label: '继续营地', onClick: () => { selectedRegion = state.region; endless = state.endless; game.ui.hideOverlay(); } }] : []), { label: '野外经验', onClick: masteryMenu }, { label: '守夜手册', onClick: guideMenu }] }); document.querySelector('#mode-choice').value = endless ? 'endless' : 'campaign'; document.querySelector('#region-choice').addEventListener('change', e => { selectedRegion = Number(e.target.value); document.querySelector('#region-detail').textContent = REGIONS[selectedRegion].desc; }); }
function craftMenu() { game.ui.overlay({ title: '篝火工坊', text: '制造时暂停。工具最多升两级，第二级消耗双倍材料。', body: inventoryHTML() + `<div class="choice-grid recipe-grid">${RECIPES.map(r => { const multiplier = r.max ? 1 + state.tools[r.id] : 1, cost = Object.fromEntries(Object.entries(r.cost).map(([k, n]) => [k, n * multiplier])), locked = r.max && state.tools[r.id] >= r.max || r.id === 'beacon' && (state.night < 10 || state.beacon), affordable = Object.entries(cost).every(([k, n]) => state.resources[k] >= n); return `<button class="choice" data-recipe="${r.id}" ${locked || !affordable ? 'disabled' : ''}><strong>${r.name}${r.max ? ' · ' + state.tools[r.id] + '/2' : ''}</strong><small>${r.desc}</small><small class="cost">${costText(cost)}${r.id === 'beacon' && state.night < 10 ? '<br>尚未获得图纸' : ''}</small></button>`; }).join('')}</div>`, buttons: [{ label: '返回营地', primary: true, onClick: () => game.ui.hideOverlay() }, { label: '营地建造', onClick: () => buildMenu() }] }); document.querySelectorAll('[data-recipe]').forEach(button => button.addEventListener('click', () => { if (craft(state, button.dataset.recipe)) { game.ui.toast('已完成：' + RECIPES.find(r => r.id === button.dataset.recipe).name); craftMenu(); } else game.ui.toast('目前无法制造：检查材料、生命或饱腹状态。'); })); }
function buildMenu() {
  const building = state.buildings.find(b => b.slot === selectedPlot);
  game.ui.overlay({ title: `营建 · ${selectedPlot + 1} 号地块`, text: '地块围绕篝火分布。面朝外的路障可拖延敌军；岗楼守住回营路线。', body: `<div class="field"><label for="plot-choice">选择地块</label><select id="plot-choice">${PLOTS.map((_, i) => `<option value="${i}" ${i === selectedPlot ? 'selected' : ''}>${i + 1} 号 · ${['南', '东南', '东', '东北', '北', '西北', '西', '西南'][i]}侧 · ${state.buildings.find(b => b.slot === i) ? BUILDINGS.find(d => d.id === state.buildings.find(b => b.slot === i).type).name : '空地'}</option>`).join('')}</select></div>${inventoryHTML()}${building ? `<p class="section-label">${BUILDINGS.find(b => b.id === building.type).name} · ${building.level} 级</p><p class="muted">耐久 ${Math.ceil(building.hp)} / ${building.maxHp}<br>${BUILDINGS.find(b => b.id === building.type).desc}</p>` : `<div class="choice-grid recipe-grid">${BUILDINGS.map(b => `<button class="choice" data-building="${b.id}" ${Object.entries(b.cost).some(([k, n]) => state.resources[k] < n) ? 'disabled' : ''}><strong>${b.name}</strong><small>${b.desc}</small><small class="cost">${costText(b.cost)}</small></button>`).join('')}</div>`}`, buttons: [...(building ? [{ label: building.level >= 3 ? '已满级' : `升级至 ${building.level + 1} 级`, disabled: building.level >= 3, onClick: () => { if (upgradeBuilding(state, selectedPlot)) buildMenu(); else game.ui.toast('升级材料不足。'); } }, { label: '修复 · 木4 石2', disabled: building.hp >= building.maxHp, onClick: () => { if (repairBuilding(state, selectedPlot)) buildMenu(); else game.ui.toast('修复材料不足。'); } }] : []), { label: '返回营地', primary: true, onClick: () => game.ui.hideOverlay() }] }); document.querySelector('#plot-choice').addEventListener('change', e => { selectedPlot = Number(e.target.value); buildMenu(); }); document.querySelectorAll('[data-building]').forEach(button => button.addEventListener('click', () => { if (build(state, selectedPlot, button.dataset.building)) { game.ui.toast('营地建筑已落成。'); buildMenu(); } else game.ui.toast('材料不足或地块已占用。'); }));
}
function masteryMenu() { game.ui.overlay({ title: '野外经验', text: `学识 ${save.knowledge} · 经验 ${save.mastery}/8`, body: '<p class="camp-story">每一夜留下的经验，<br>会让下一次出发更从容。</p><p class="muted">每级增加 5 起始生命、12 营火耐久与 2 木材。守住夜晚、护送幸存者与成功撤离均获得学识。</p>', buttons: [{ label: `学习经验 · ${25 + save.mastery * 20}`, primary: true, disabled: save.mastery >= 8, onClick: () => { const next = buyMastery(save); if (!next) game.ui.toast('学识不足，继续守夜后再来。'); else { save = next; game.save(save); masteryMenu(); } } }, { label: '返回', onClick: menu }] }); }
function guideMenu() { game.ui.overlay({ title: '十五夜守望手册', text: '普通旅程须守过十五夜、救回三名幸存者并造好救援信标。无尽模式持续守卫，直到营火或玩家倒下。', body: `<div class="choice-grid"><div class="choice"><strong>白天准备</strong><small>采集木石，优先精制斧与岗楼。备好燃料与食物。每个白天 42 秒，也可提前入夜。</small></div><div class="choice"><strong>晚上守卫</strong><small>近处 Space 挥矛，岗楼自动射击。路障分担伤害；燃料用尽会持续损伤营火。</small></div><div class="choice"><strong>求救信号</strong><small>第 3、6、9、12 天出现失散者。靠近 E 开始护送，走回营火才能完成救援。救回的人增强岗楼。</small></div><div class="choice"><strong>营地成长</strong><small>菜圃黎明产食物，窑炉产矿；帐篷治疗，冷凝器修营火。药包与炖菜能在制造菜单立即使用。</small></div></div><p class="section-label">夜袭篇章</p><div class="night-list">${NIGHTS.map(n => `<span>${String(n.night).padStart(2, '0')} · ${n.title}${n.boss ? ' · 首领' : ''}</span>`).join('')}</div><p class="muted">每局结算后自动保存学识与最佳夜数。页面刷新会开始新营地。</p>`, buttons: [{ label: '返回', primary: true, onClick: menu }] }); }
function finish() { const before = save.knowledge; save = settleExpedition(state, save); game.save(save); game.ui.overlay({ title: state.phase === 'won' ? '信标亮起，我们回家。' : '这一次，火光暂歇。', text: `${REGIONS[state.region].name} · 守过 ${Math.max(0, state.night - (state.phase === 'won' ? 0 : 1))} 夜\n救援 ${state.rescued} 人 · 击退 ${state.kills} · 获得学识 ${save.knowledge - before}`, body: `<p class="camp-story">${state.phase === 'won' ? '十五个夜晚之后，<br>每一个等待的人都有了归途。' : '先备木柴，再修防线。<br>下一次的你，已经懂得更多。'}</p>`, buttons: [{ label: '再次扎营', primary: true, onClick: start }, { label: '选择区域', onClick: menu }, { label: '学习经验', onClick: masteryMenu }] }); }
function nightAction() { if (beginNight(state)) { game.ui.toast(`第 ${state.night} 夜 · ${NIGHTS[Math.min(14, state.night - 1)].title}`); game.sound(180, .25, 'triangle'); } }
dock.querySelector('.craft-button').addEventListener('click', craftMenu); dock.querySelector('.build-button').addEventListener('click', () => buildMenu()); dock.querySelector('.night-button').addEventListener('click', nightAction);
game.onMenu(menu); state = createExpedition(); scenery(); game.camera.position.set(0, 30, 25); render(.1); menu();
game.run(dt => {
  if (game.input.pressed('KeyQ')) { craftMenu(); return; } if (game.input.pressed('KeyB')) { selectedPlot = PLOTS.reduce((nearest, p, i) => Math.hypot(p.x - state.player.x, p.z - state.player.z) < Math.hypot(PLOTS[nearest].x - state.player.x, PLOTS[nearest].z - state.player.z) ? i : nearest, 0); buildMenu(); return; } if (game.input.pressed('KeyN')) nightAction();
  stepExpedition(state, { x: game.input.axis('x'), z: game.input.axis('y'), interact: game.input.held('KeyE'), attack: game.input.held('Space') }, dt); render(dt);
  for (const event of state.events) { if (event.type === 'gather' && state.time - lastSound > .15) { game.sound(340, .08, 'triangle', .03); lastSound = state.time; } if (event.type === 'hurt') game.sound(100, .15, 'triangle'); if (event.type === 'rescued') game.ui.toast(`幸存者已回营 · 已救援 ${state.rescued}/3`); if (event.type === 'signal') game.ui.toast('林间出现求救信号，跟随提示寻找失散者。'); if (event.type === 'dawn') game.ui.toast('黎明到来 · 菜圃与窑炉已产出物资'); }
  if (state.phase !== lastPhase) { lastPhase = state.phase; if (state.phase === 'won' || state.phase === 'lost') finish(); }
});
